# -*- coding: utf-8 -*-
"""algoritmos_clasicos_evaluacion_final_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gLyBJ5_59As4pa0iJvlN0xWbC_0Oin-S
"""

# ══════════════════════════════════════════════════════════════
# EVALUACIÓN FINAL EN TEST — MEJORES CONFIGS POR ALGORITMO
# Split genuino 70/15/15 — sin re-entrenamiento
#
# Flujo:
#   1. Se cargan las 4 mejores configs (una por algoritmo),
#      elegidas por F1 Macro en validación en la búsqueda previa
#   2. Cada algoritmo se entrena sobre train (70%)
#   3. Umbral óptimo buscado en val (0.50-0.60, paso 0.005)
#      → IDÉNTICO al procedimiento de los Transformers
#   4. Evaluación final en test (15%) UNA SOLA VEZ por algoritmo
#   5. Se reportan los 4 resultados de forma independiente
#      → comparable con BETO / mBERT / XLM-RoBERTa
#
# Simetría con Transformers:
#   - Mismo split 70/15/15 con seed=42
#   - Mismo rango de umbral: np.arange(0.50, 0.601, 0.005)
#   - Mismo criterio de selección: F1 Macro en validación
#   - Mismo manejo de desbalanceo: class_weight='balanced'
#   - Sin re-entrenamiento: train 70% en ambos lados
# ══════════════════════════════════════════════════════════════

import zipfile, io, json, time, os
import numpy as np
import pandas as pd
import nltk
import matplotlib
import matplotlib.pyplot as plt
matplotlib.use('Agg')

from datetime import datetime
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, classification_report, confusion_matrix
)

# ── 1. MONTAR DRIVE ───────────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

# ── 2. CONFIGURACIÓN ──────────────────────────────────────────
ZIP_PATH      = "/content/drive/MyDrive/PyCrim_dataset.zip"
ZIP_ARCHIVO   = "corpusJurisprudence.txt"
OUTPUT_DIR    = "/content/drive/MyDrive/Proyecto/PyCrim_experiments/CLASICOS"
os.makedirs(OUTPUT_DIR, exist_ok=True)

SEMILLA       = 42
COLUMNA_TEXTO = "Contenido Txt"
COLUMNA_LABEL = "Resultado binario de la acción"

inicio = time.time()

# ── 3. CARGAR DATASET ─────────────────────────────────────────
with zipfile.ZipFile(ZIP_PATH, "r") as z:
    datos = io.BytesIO(z.read(ZIP_ARCHIVO))
data = pd.read_csv(datos, sep="\t")
print(f"Dataset: {data.shape}")

# ── 4. SPLIT 70/15/15 — IDÉNTICO AL DE TRANSFORMERS ──────────
train_df, temp_df = train_test_split(
    data, test_size=0.30,
    stratify=data[COLUMNA_LABEL], random_state=SEMILLA
)
val_df, test_df = train_test_split(
    temp_df, test_size=0.50,
    stratify=temp_df[COLUMNA_LABEL], random_state=SEMILLA
)

X_train = train_df[COLUMNA_TEXTO].reset_index(drop=True)
y_train = train_df[COLUMNA_LABEL].reset_index(drop=True)
X_val   = val_df[COLUMNA_TEXTO].reset_index(drop=True)
y_val   = val_df[COLUMNA_LABEL].reset_index(drop=True)
X_test  = test_df[COLUMNA_TEXTO].reset_index(drop=True)
y_test  = test_df[COLUMNA_LABEL].reset_index(drop=True)

print(f"Train: {len(X_train)} | Val: {len(X_val)} | Test: {len(X_test)}")

# ── 5. PREPROCESAMIENTO ───────────────────────────────────────
nltk.download("punkt",     quiet=True)
nltk.download("punkt_tab", quiet=True)
nltk.download("stopwords", quiet=True)

stemmer           = SnowballStemmer("spanish")
spanish_stopwords = stopwords.words("spanish")

def tokenize_and_stem(text):
    tokens = nltk.word_tokenize(text.lower())
    return [stemmer.stem(t) for t in tokens]

def tokenize_and_stem_stop(text):
    tokens = nltk.word_tokenize(text.lower())
    tokens = [w for w in tokens if w not in spanish_stopwords]
    return [stemmer.stem(t) for t in tokens]

print("\n✅ Setup completo")

# ── 6. MEJORES CONFIGURACIONES (elegidas en validación) ───────
# Estas configs fueron seleccionadas por F1 Macro en val
# en la búsqueda exhaustiva de 64 configuraciones previa.
# NO se modifican aquí — el val set ya cumplió su rol.

MEJORES_CONFIGS = {
    #        ng  sw  st  min_df  tfidf   f1_val
    "NB":  { "ng": 4, "sw": 0, "st": 1, "mn": 2, "tf": 0, "f1_val": 0.7835 },
    "LR":  { "ng": 4, "sw": 0, "st": 1, "mn": 3, "tf": 0, "f1_val": 0.8146 },
    "RF":  { "ng": 4, "sw": 1, "st": 1, "mn": 2, "tf": 0, "f1_val": 0.7850 },
    "SVM": { "ng": 4, "sw": 1, "st": 1, "mn": 3, "tf": 1, "f1_val": 0.8192 },
}

print("Configuraciones seleccionadas en validación:")
print("-" * 65)
for algo, cfg in MEJORES_CONFIGS.items():
    vect = "TF-IDF" if cfg['tf'] == 1 else "TF"
    sw   = "Con" if cfg['sw'] == 1 else "Sin"
    st   = "Con" if cfg['st'] == 1 else "Sin"
    print(f"{algo:4s} → ng={cfg['ng']} sw={sw:3s} st={st:3s} "
          f"min_df={cfg['mn']} {vect:6s}  F1_val={cfg['f1_val']:.4f}")
print("-" * 65)

# ── 7. FUNCIONES AUXILIARES ───────────────────────────────────

def construir_vectorizador(ng, sw, st, mn, tf):
    """Construye el vectorizador con los parámetros dados."""
    token_pattern_var = r"(?u)\b\w+\b"
    stop_word_var     = None
    tokenizer_var     = None

    if sw == 1 and st == 0:
        stop_word_var = spanish_stopwords
    elif sw == 0 and st == 1:
        tokenizer_var     = tokenize_and_stem
        token_pattern_var = None
    elif sw == 1 and st == 1:
        tokenizer_var     = tokenize_and_stem_stop
        token_pattern_var = None

    params = {
        "ngram_range":   (ng, ng),
        "stop_words":    stop_word_var,
        "tokenizer":     tokenizer_var,
        "token_pattern": token_pattern_var,
        "min_df":        mn,
    }
    return CountVectorizer(**params) if tf == 0 else TfidfVectorizer(**params)


def entrenar_modelo(algo, ng, sw, st, mn, tf):
    """Entrena el modelo sobre train (70%) con la config dada."""
    vect        = construir_vectorizador(ng, sw, st, mn, tf)
    X_train_vec = vect.fit_transform(X_train)
    scaler      = None

    if algo == "NB":
        # class_prior uniforme — compensa desbalanceo 80/20
        modelo = MultinomialNB(alpha=0.1, class_prior=[0.5, 0.5])
        modelo.fit(X_train_vec, y_train)

    elif algo == "LR":
        # class_weight='balanced' — alineado con Transformers
        modelo = LogisticRegression(max_iter=2000, random_state=SEMILLA,
                                    class_weight='balanced')
        modelo.fit(X_train_vec, y_train)

    elif algo == "RF":
        # class_weight='balanced' — alineado con Transformers
        modelo = RandomForestClassifier(n_estimators=100, random_state=SEMILLA,
                                        class_weight='balanced')
        modelo.fit(X_train_vec, y_train)

    else:  # SVM
        # class_weight='balanced' — alineado con Transformers
        # probability=True — necesario para predict_proba y búsqueda de umbral
        scaler      = StandardScaler(with_mean=False)
        X_train_vec = scaler.fit_transform(X_train_vec)
        modelo      = SVC(kernel="linear", max_iter=-1, random_state=SEMILLA,
                          class_weight='balanced', probability=True)
        modelo.fit(X_train_vec, y_train)

    return modelo, vect, scaler


def buscar_umbral_optimo(modelo, vect, scaler, algo):
    """
    Busca el umbral óptimo sobre VALIDACIÓN.
    Rango e implementación IDÉNTICOS a los Transformers:
        np.arange(0.50, 0.601, 0.005)
    """
    X_val_vec = vect.transform(X_val)
    if algo == "SVM":
        X_val_vec = scaler.transform(X_val_vec)

    proba = modelo.predict_proba(X_val_vec)[:, 1]

    # ── Mismo rango que Transformers ──────────────────────────
    thresholds       = np.arange(0.50, 0.601, 0.005)
    resultados_umbral = []
    for t in thresholds:
        preds = (proba >= t).astype(int)
        f1_t  = f1_score(y_val, preds, average="macro", zero_division=0)
        resultados_umbral.append((round(float(t), 3), round(f1_t, 4)))

    mejor_t, mejor_f1 = max(resultados_umbral, key=lambda x: x[1])

    print(f"  Top 5 umbrales ({algo}):")
    for t, f in sorted(resultados_umbral, key=lambda x: x[1], reverse=True)[:5]:
        print(f"    umbral={t:.3f} → F1 Macro val={f:.4f}")
    print(f"  ✅ Umbral óptimo: {mejor_t:.3f} (F1 val={mejor_f1:.4f})")

    return mejor_t, mejor_f1


def evaluar_en_test(modelo, vect, scaler, algo, umbral):
    """Evalúa el modelo en test con el umbral óptimo."""
    X_test_vec = vect.transform(X_test)
    if algo == "SVM":
        X_test_vec = scaler.transform(X_test_vec)

    proba       = modelo.predict_proba(X_test_vec)[:, 1]
    predictions = (proba >= umbral).astype(int)
    return predictions


print("✅ Funciones definidas")

# ── 8. EVALUACIÓN FINAL — UN ALGORITMO POR VEZ ────────────────
# Cada algoritmo se evalúa de forma independiente en test,
# comparable con la evaluación independiente de cada Transformer.

resultados_finales = {}

for algo, cfg in MEJORES_CONFIGS.items():
    print(f"\n{'='*60}")
    print(f"ALGORITMO: {algo}")
    print(f"Config: ng={cfg['ng']} sw={cfg['sw']} st={cfg['st']} "
          f"min_df={cfg['mn']} tfidf={cfg['tf']}")
    print(f"Entrenando sobre {len(X_train)} instancias (train 70%)...")

    # Entrenar sobre train (70%) — sin re-entrenamiento
    modelo, vect, scaler = entrenar_modelo(
        algo, cfg['ng'], cfg['sw'], cfg['st'], cfg['mn'], cfg['tf']
    )
    print(f"  Entrenamiento completado")

    # Buscar umbral en val — idéntico a Transformers
    umbral, f1_val_umbral = buscar_umbral_optimo(modelo, vect, scaler, algo)

    # Evaluar en test UNA SOLA VEZ
    predictions = evaluar_en_test(modelo, vect, scaler, algo, umbral)

    # Métricas
    cm       = confusion_matrix(y_test, predictions)
    acc      = accuracy_score(y_test, predictions)
    f1       = f1_score(y_test, predictions, average="macro")
    prec     = precision_score(y_test, predictions, average="macro", zero_division=1)
    rec      = recall_score(y_test, predictions, average="macro")
    f1_pos   = f1_score(y_test, predictions, pos_label=1, average="binary")
    f1_neg   = f1_score(y_test, predictions, pos_label=0, average="binary")
    prec_pos = precision_score(y_test, predictions, pos_label=1, average="binary", zero_division=1)
    rec_pos  = recall_score(y_test, predictions, pos_label=1, average="binary")

    resultados_finales[algo] = {
        "config":         cfg,
        "umbral":         umbral,
        "f1_val_umbral":  f1_val_umbral,
        "f1_val_config":  cfg['f1_val'],
        "acc":            round(acc,      4),
        "f1":             round(f1,       4),
        "prec":           round(prec,     4),
        "rec":            round(rec,      4),
        "f1_pos":         round(f1_pos,   4),
        "f1_neg":         round(f1_neg,   4),
        "prec_pos":       round(prec_pos, 4),
        "rec_pos":        round(rec_pos,  4),
        "cm":             cm,
        "predictions":    predictions,
    }

    print(f"\n  RESULTADO EN TEST:")
    print(classification_report(
        y_test, predictions,
        target_names=["No hace lugar (0)", "Hace lugar (1)"],
        digits=4
    ))
    print(f"  F1 Macro test:            {f1:.4f}")
    print(f"  F1 Clase Positiva test:   {f1_pos:.4f}")
    print(f"  Umbral utilizado:         {umbral:.3f}")

    # Guardar predicciones para Bootstrap / McNemar
    np.save(os.path.join(OUTPUT_DIR, f"y_true_CLASICO_{algo}.npy"), y_test.values)
    np.save(os.path.join(OUTPUT_DIR, f"y_pred_CLASICO_{algo}.npy"), predictions)

print(f"\n{'='*60}")
print("✅ Evaluación final completada para los 4 algoritmos")

# ── 9. TABLA RESUMEN COMPARATIVA ──────────────────────────────
print("\n" + "="*70)
print("RESUMEN COMPARATIVO — ALGORITMOS CLÁSICOS")
print("Split 70/15/15 · sin re-entrenamiento · umbral optimizado en val")
print("="*70)
print(f"{'Algoritmo':<8} {'F1_val':>8} {'F1_test':>8} "
      f"{'F1_pos':>8} {'F1_neg':>8} {'Rec_pos':>8} {'Umbral':>8}")
print("-"*70)
for algo, r in resultados_finales.items():
    print(f"{algo:<8} {r['f1_val_config']:>8.4f} {r['f1']:>8.4f} "
          f"{r['f1_pos']:>8.4f} {r['f1_neg']:>8.4f} "
          f"{r['rec_pos']:>8.4f} {r['umbral']:>8.3f}")
print("="*70)

mejor_algo = max(resultados_finales, key=lambda a: resultados_finales[a]['f1'])
print(f"\nMejor algoritmo en test: {mejor_algo} "
      f"(F1 Macro = {resultados_finales[mejor_algo]['f1']:.4f})")

# ── 10. MATRICES DE CONFUSIÓN (2×2 grid) ──────────────────────
fig, axes = plt.subplots(2, 2, figsize=(12, 10))
etiquetas = ["No hace lugar (0)", "Hace lugar (1)"]

for ax, (algo, r) in zip(axes.flatten(), resultados_finales.items()):
    cm    = r['cm']
    total = cm.sum()
    im    = ax.imshow(cm, interpolation="nearest", cmap="Blues")
    plt.colorbar(im, ax=ax)
    ax.set(
        xticks=[0, 1], yticks=[0, 1],
        xticklabels=etiquetas, yticklabels=etiquetas,
        ylabel="Etiqueta real", xlabel="Etiqueta predicha",
        title=(
            f"{algo} — F1 Macro={r['f1']:.4f}\n"
            f"Umbral={r['umbral']:.3f} · Split 70/15/15"
        )
    )
    for i in range(2):
        for j in range(2):
            v     = cm[i, j]
            color = "white" if v > cm.max() / 2 else "black"
            ax.text(j, i, f"{v}\n({v/total*100:.1f}%)",
                    ha="center", va="center",
                    fontsize=11, color=color, fontweight="bold")
    ax.set_xticklabels(etiquetas, rotation=15, ha="right")

plt.suptitle(
    "Matrices de Confusión — Algoritmos Clásicos\n"
    "Split 70/15/15 · sin re-entrenamiento · umbral optimizado en val",
    fontsize=13, fontweight="bold"
)
plt.tight_layout()

PNG_PATH = os.path.join(OUTPUT_DIR, "confusion_matrices_CLASICOS_4algofin.png")
plt.savefig(PNG_PATH, dpi=150, bbox_inches="tight")
plt.show()
print(f"✅ PNG guardado: {PNG_PATH}")

# ── 11. GUARDAR JSON CONSOLIDADO ──────────────────────────────
tiempo = round((time.time() - inicio) / 60, 2)

config_json = {
    "experimento": {
        "id":          "CLASICO-EVALUACION-FINAL-4ALGO-70-15-15",
        "fecha":       datetime.now().strftime("%Y-%m-%d %H:%M"),
        "responsable": "Fatima Ferreira - Blanca Franco",
        "descripcion": (
            "Evaluación final en test de los 4 mejores algoritmos clásicos. "
            "Configs elegidas por F1 Macro en validación (búsqueda previa de 64 configs). "
            "Split genuino 70/15/15 estratificado (seed=42), idéntico a Transformers. "
            "Sin re-entrenamiento: train 70% en ambos lados. "
            "Umbral buscado en val con np.arange(0.50, 0.601, 0.005), "
            "idéntico al procedimiento de los Transformers. "
            "class_weight=balanced en LR/RF/SVM, class_prior=[0.5,0.5] en NB."
        ),
    },
    "simetria_con_transformers": {
        "split":           "70/15/15 estratificado, seed=42",
        "entrenamiento":   "train 70% únicamente, sin re-entrenamiento",
        "umbral_rango":    "np.arange(0.50, 0.601, 0.005)",
        "umbral_criterio": "F1 Macro en validación",
        "desbalanceo":     "class_weight=balanced / class_prior uniforme",
        "evaluacion":      "test 15%, una sola vez por algoritmo",
    },
    "datos": {
        "dataset":        "PyCrim",
        "total":          len(data),
        "train":          len(X_train),
        "val":            len(X_val),
        "test":           len(X_test),
        "balance_test": {
            "clase_0_n":   int((y_test == 0).sum()),
            "clase_1_n":   int((y_test == 1).sum()),
            "clase_0_pct": round((y_test == 0).sum() / len(y_test) * 100, 2),
            "clase_1_pct": round((y_test == 1).sum() / len(y_test) * 100, 2),
        },
    },
    "resultados": {
        "tiempo_minutos": tiempo,
        "algoritmos": {
            algo: {
                "configuracion": {
                    "ngram_range": r['config']['ng'],
                    "stop_words":  "Con" if r['config']['sw'] == 1 else "Sin",
                    "stemming":    "Con" if r['config']['st'] == 1 else "Sin",
                    "min_df":      r['config']['mn'],
                    "vectorizador": "TF-IDF" if r['config']['tf'] == 1 else "TF",
                    "f1_macro_val_config": r['f1_val_config'],
                },
                "umbral_decision":      r['umbral'],
                "f1_macro_val_umbral":  r['f1_val_umbral'],
                "test": {
                    "exactitud":                    r['acc'],
                    "f1_macro":                     r['f1'],
                    "f1_clase_positiva":            r['f1_pos'],
                    "f1_clase_negativa":            r['f1_neg'],
                    "precision_macro":              r['prec'],
                    "exhaustividad_macro":          r['rec'],
                    "precision_clase_positiva":     r['prec_pos'],
                    "exhaustividad_clase_positiva": r['rec_pos'],
                },
                "matriz_confusion": {
                    "TP": int(r['cm'][1, 1]),
                    "TN": int(r['cm'][0, 0]),
                    "FP": int(r['cm'][0, 1]),
                    "FN": int(r['cm'][1, 0]),
                },
            }
            for algo, r in resultados_finales.items()
        },
    },
}

JSON_PATH = os.path.join(OUTPUT_DIR, "resultados_CLASICOS_4algo_70_15_15fin.json")
with open(JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(config_json, f, ensure_ascii=False, indent=2)
print(f"✅ JSON guardado: {JSON_PATH}")