# -*- coding: utf-8 -*-
"""algoritmos_clasicos_70_15_15_busqueda64config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JHtYGZiRxWUAg97JyIWd7hyxPgGbsO7E
"""

# ══════════════════════════════════════════════════════════════
# BÚSQUEDA EXHAUSTIVA — 64 CONFIGURACIONES — ALGORITMOS CLÁSICOS
# Split GENUINO 70/15/15 estratificado — SIN re-entrenamiento
# Comparación directa y simétrica con experimentos Transformer
# OBSERVACION: Este codigo finalmente solo se uso para elegir la mejor configuracion,
# en el archivo algoritmos_clasicos_evaluacion_final_test.py se realiza la prueba con el umbral alineado con el de transformers np.arange(0.50, 0.601, 0.005) en vez de np.arange(0.20, 0.81, 0.01)
#
# Flujo:
#   1. Split 70/15/15 idéntico al de los Transformers (seed=42)
#   2. Las 64 configuraciones se entrenan en train (70%) y
#      se evalúan sobre VALIDACIÓN (15%)
#   3. Se elige la mejor configuración por F1 Macro en validación
#   4. El modelo ya entrenado en 70% se evalúa UNA SOLA VEZ en test
#      → NO se re-entrena, garantizando split genuino 70/15/15
#
# Mejoras respecto al notebook anterior:
#   - class_weight='balanced' en LR, RF, SVM  (alineado con Transformers)
#   - class_prior=[0.5, 0.5] en NB             (alineado con Transformers)
#   - Umbral de decisión optimizado en val
#   - Sin re-entrenamiento: split genuinamente 70/15/15 en ambos lados
# ══════════════════════════════════════════════════════════════

import zipfile
import io
import json
import time
import os
import numpy as np
import pandas as pd
import nltk
import matplotlib
import matplotlib.pyplot as plt
matplotlib.use('Agg')

from datetime import datetime
from itertools import product
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, classification_report, confusion_matrix
)

# ── 1. MONTAR DRIVE ───────────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

# ── 2. CONFIGURACIÓN ──────────────────────────────────────────
ZIP_PATH    = "/content/drive/MyDrive/PyCrim_dataset.zip"
ZIP_ARCHIVO = "corpusJurisprudence.txt"
OUTPUT_DIR  = "/content/drive/MyDrive/Proyecto/PyCrim_experiments/CLASICOS"
os.makedirs(OUTPUT_DIR, exist_ok=True)

SEMILLA = 42   # idéntico a todos los experimentos Transformer

COLUMNA_TEXTO = "Contenido Txt"
COLUMNA_LABEL = "Resultado binario de la acción"

inicio = time.time()

# ── 3. CARGAR DATASET ─────────────────────────────────────────
with zipfile.ZipFile(ZIP_PATH, "r") as zipref:
    datos = io.BytesIO(zipref.read(ZIP_ARCHIVO))

data = pd.read_csv(datos, sep="\t")
print(f"Dataset cargado: {data.shape}")
print("\nDistribución de clases (dataset completo):")
print(data[COLUMNA_LABEL].value_counts())
print(data[COLUMNA_LABEL].value_counts(normalize=True).round(3))

# ── 4. SPLIT 70/15/15 ESTRATIFICADO ───────────────────────────
# Replicando EXACTAMENTE el mismo proceso que los experimentos Transformer
# Paso 1: separar 70% train del 30% restante
train_df, temp_df = train_test_split(
    data, test_size=0.30,
    stratify=data[COLUMNA_LABEL],
    random_state=SEMILLA
)
# Paso 2: dividir el 30% en 15% val y 15% test
val_df, test_df = train_test_split(
    temp_df, test_size=0.50,
    stratify=temp_df[COLUMNA_LABEL],
    random_state=SEMILLA
)

X_train = train_df[COLUMNA_TEXTO].reset_index(drop=True)
y_train = train_df[COLUMNA_LABEL].reset_index(drop=True)
X_val   = val_df[COLUMNA_TEXTO].reset_index(drop=True)
y_val   = val_df[COLUMNA_LABEL].reset_index(drop=True)
X_test  = test_df[COLUMNA_TEXTO].reset_index(drop=True)
y_test  = test_df[COLUMNA_LABEL].reset_index(drop=True)

print(f"\nTrain: {len(X_train)} ({len(X_train)/len(data)*100:.1f}%)")
print(f"Val:   {len(X_val)}  ({len(X_val)/len(data)*100:.1f}%)")
print(f"Test:  {len(X_test)}  ({len(X_test)/len(data)*100:.1f}%)")
print("\nDistribución clases — train:", y_train.value_counts(normalize=True).round(3).to_dict())
print("Distribución clases — val:  ", y_val.value_counts(normalize=True).round(3).to_dict())
print("Distribución clases — test: ", y_test.value_counts(normalize=True).round(3).to_dict())

# ── 5. PREPROCESAMIENTO ───────────────────────────────────────
nltk.download("punkt", quiet=True)
nltk.download("punkt_tab", quiet=True)
nltk.download("stopwords", quiet=True)

stemmer           = SnowballStemmer("spanish")
spanish_stopwords = stopwords.words("spanish")

def stem_tokens(tokens):
    return [stemmer.stem(t) for t in tokens]

def tokenize_and_stem(text):
    tokens = nltk.word_tokenize(text.lower())
    return stem_tokens(tokens)

def tokenize_and_stem_stop(text):
    tokens = nltk.word_tokenize(text.lower())
    tokens = [w for w in tokens if w not in spanish_stopwords]
    return stem_tokens(tokens)

print("\n✅ Setup completo")

# ── 6. BÚSQUEDA EXHAUSTIVA — 64 CONFIGURACIONES ───────────────
# Entrena sobre TRAIN (70%) y evalúa sobre VALIDACIÓN (15%)
# El modelo entrenado en train se GUARDA para reutilizarlo en test
# sin necesidad de re-entrenar (split genuinamente 70/15/15)

def construir_vectorizador(param0, param1, param2, param3, param4):
    """
    Construye el vectorizador con los parámetros dados.
    param0: ngramas (1,2,3,4)
    param1: stopwords (0=sin, 1=con)
    param2: stemming  (0=sin, 1=con)
    param3: min_df    (2, 3)
    param4: vectorizador (0=CountVectorizer, 1=TF-IDF)
    """
    token_pattern_var = r"(?u)\b\w+\b"
    stop_word_var     = None
    tokenizer_var     = None

    if param1 == 1 and param2 == 0:
        stop_word_var = spanish_stopwords
    elif param1 == 0 and param2 == 1:
        tokenizer_var     = tokenize_and_stem
        token_pattern_var = None
    elif param1 == 1 and param2 == 1:
        tokenizer_var     = tokenize_and_stem_stop
        token_pattern_var = None

    params = {
        "ngram_range":   (param0, param0),
        "stop_words":    stop_word_var,
        "tokenizer":     tokenizer_var,
        "token_pattern": token_pattern_var,
        "min_df":        param3,
    }
    return CountVectorizer(**params) if param4 == 0 else TfidfVectorizer(**params)


def entrenar_y_evaluar_val(param0, param1, param2, param3, param4):
    """
    Entrena sobre X_train (70%) y evalúa sobre X_val (15%).
    Devuelve los modelos entrenados y sus métricas en validación.
    Los modelos se guardan para evaluación directa en test SIN re-entrenar.
    """
    vect     = construir_vectorizador(param0, param1, param2, param3, param4)
    X_tr_vec = vect.fit_transform(X_train)
    X_vl_vec = vect.transform(X_val)

    resultados = {}

    def metricas_val(preds):
        return {
            "acc":  round(accuracy_score(y_val, preds), 4),
            "prec": round(precision_score(y_val, preds, average="macro", zero_division=1), 4),
            "rec":  round(recall_score(y_val, preds, average="macro"), 4),
            "f1":   round(f1_score(y_val, preds, average="macro"), 4),
        }

    # ── Naive Bayes ──────────────────────────────────────────
    # class_prior=[0.5, 0.5]: uniforme para compensar desbalanceo 80/20,
    # alineado con class_weight='balanced' de los demás algoritmos
    nb = MultinomialNB(alpha=0.1, class_prior=[0.5, 0.5])
    nb.fit(X_tr_vec, y_train)
    resultados["NB"] = {
        "model": nb, "vect": vect, "scaler": None,
        **metricas_val(nb.predict(X_vl_vec))
    }

    # ── Logistic Regression ──────────────────────────────────
    # class_weight='balanced' compensa desbalanceo 80/20,
    # alineado con compute_class_weight de los Transformers
    lr = LogisticRegression(max_iter=2000, random_state=SEMILLA,
                            class_weight='balanced')
    lr.fit(X_tr_vec, y_train)
    resultados["LR"] = {
        "model": lr, "vect": vect, "scaler": None,
        **metricas_val(lr.predict(X_vl_vec))
    }

    # ── Random Forest ────────────────────────────────────────
    # class_weight='balanced' compensa desbalanceo 80/20
    rf = RandomForestClassifier(n_estimators=100, random_state=SEMILLA,
                                class_weight='balanced')
    rf.fit(X_tr_vec, y_train)
    resultados["RF"] = {
        "model": rf, "vect": vect, "scaler": None,
        **metricas_val(rf.predict(X_vl_vec))
    }

    # ── SVM ──────────────────────────────────────────────────
    # class_weight='balanced' compensa desbalanceo 80/20
    # probability=True habilita predict_proba para búsqueda de umbral
    scaler      = StandardScaler(with_mean=False)
    X_tr_scaled = scaler.fit_transform(X_tr_vec)
    X_vl_scaled = scaler.transform(X_vl_vec)
    svm = SVC(kernel="linear", max_iter=-1, random_state=SEMILLA,
              class_weight='balanced', probability=True)
    svm.fit(X_tr_scaled, y_train)
    resultados["SVM"] = {
        "model": svm, "vect": vect, "scaler": scaler,
        **metricas_val(svm.predict(X_vl_scaled))
    }

    return resultados


# ── Búsqueda de umbral óptimo en validación ───────────────────
# Alineado con Transformers: el umbral se busca en val, nunca en test
def buscar_umbral_optimo(modelo, vect, scaler, algo):
    """Busca el umbral de decisión que maximiza F1 Macro en validación."""
    X_vl_vec = vect.transform(X_val)
    if algo == "SVM":
        X_vl_vec = scaler.transform(X_vl_vec)
    proba = modelo.predict_proba(X_vl_vec)[:, 1]

    mejor_t, mejor_f1 = 0.5, -1
    for t in np.arange(0.20, 0.81, 0.01):
        preds = (proba >= t).astype(int)
        f1_t  = f1_score(y_val, preds, average="macro", zero_division=0)
        if f1_t > mejor_f1:
            mejor_f1, mejor_t = f1_t, round(float(t), 2)
    return mejor_t, round(mejor_f1, 4)


# ── Iterar las 64 combinaciones ───────────────────────────────
combinaciones   = list(product([1,2,3,4], [0,1], [0,1], [2,3], [0,1]))
CHECKPOINT_FILE = os.path.join(OUTPUT_DIR, "resultados_val_70_15_15.csv")

cols = [
    "ng", "sw", "st", "min_df", "tfidf",
    "NB_f1",  "NB_acc",  "NB_prec",  "NB_rec",
    "LR_f1",  "LR_acc",  "LR_prec",  "LR_rec",
    "RF_f1",  "RF_acc",  "RF_prec",  "RF_rec",
    "SVM_f1", "SVM_acc", "SVM_prec", "SVM_rec",
]

if os.path.exists(CHECKPOINT_FILE):
    df_resultados = pd.read_csv(CHECKPOINT_FILE)
    print(f"Checkpoint encontrado: {len(df_resultados)} configuraciones ya procesadas")
else:
    df_resultados = pd.DataFrame(columns=cols)

# Guardar también los modelos de las mejores configuraciones por algoritmo
# para evitar re-entrenar al momento de evaluar en test
modelos_guardados = {}   # {(ng,sw,st,mn,tf): {"NB":{model,vect,...}, ...}}

print(f"Total configuraciones a evaluar: {len(combinaciones)}")
print(f"Entrenamiento: {len(X_train)} instancias (train 70%)")
print(f"Selección:     {len(X_val)}  instancias (val 15%)")
print(f"Evaluación:    {len(X_test)}  instancias (test 15%)\n")

for i, (ng, sw, st, mn, tf) in enumerate(combinaciones):
    key = (ng, sw, st, mn, tf)
    ya  = (
        (df_resultados["ng"]     == ng) &
        (df_resultados["sw"]     == sw) &
        (df_resultados["st"]     == st) &
        (df_resultados["min_df"] == mn) &
        (df_resultados["tfidf"]  == tf)
    ).any()

    if not ya:
        res = entrenar_y_evaluar_val(ng, sw, st, mn, tf)
        modelos_guardados[key] = res

        nueva_fila = [
            ng, sw, st, mn, tf,
            res["NB"]["f1"],  res["NB"]["acc"],  res["NB"]["prec"],  res["NB"]["rec"],
            res["LR"]["f1"],  res["LR"]["acc"],  res["LR"]["prec"],  res["LR"]["rec"],
            res["RF"]["f1"],  res["RF"]["acc"],  res["RF"]["prec"],  res["RF"]["rec"],
            res["SVM"]["f1"], res["SVM"]["acc"], res["SVM"]["prec"], res["SVM"]["rec"],
        ]
        df_resultados = pd.concat(
            [df_resultados, pd.DataFrame([nueva_fila], columns=cols)],
            ignore_index=True
        )
        df_resultados.to_csv(CHECKPOINT_FILE, index=False)

    if (i + 1) % 8 == 0:
        print(f"  {i+1}/64 configuraciones procesadas...")

print("\n✅ Búsqueda exhaustiva completada")
print(df_resultados[["ng","sw","st","min_df","tfidf",
                      "NB_f1","LR_f1","RF_f1","SVM_f1"]].to_string(index=False))

# ── 7. SELECCIONAR MEJOR CONFIGURACIÓN POR VALIDACIÓN ─────────

algoritmos   = ["NB", "LR", "RF", "SVM"]
mejor_global = {"algoritmo": None, "config": None, "f1_val": -1}

print("Mejor configuración por algoritmo (F1 Macro en VALIDACIÓN):")
print("-" * 65)

for algo in algoritmos:
    col  = f"{algo}_f1"
    idx  = df_resultados[col].idxmax()
    fila = df_resultados.loc[idx]
    print(f"{algo:4s} → ng={int(fila.ng)} sw={int(fila.sw)} "
          f"st={int(fila.st)} min_df={int(fila.min_df)} "
          f"tfidf={int(fila.tfidf)}  F1_val={fila[col]:.4f}")

    if fila[col] > mejor_global["f1_val"]:
        mejor_global = {
            "algoritmo": algo,
            "config":    fila,
            "f1_val":    fila[col]
        }

print("-" * 65)
print(f"\nMEJOR GLOBAL en validación: {mejor_global['algoritmo']} "
      f"con F1 Macro val = {mejor_global['f1_val']:.4f}")

# ── 8. EVALUACIÓN FINAL SOBRE PRUEBA — SIN RE-ENTRENAMIENTO ───
# Se usa el modelo ya entrenado en train (70%).
# NO se re-entrena, garantizando split genuinamente 70/15/15
# en ambos lados (clásicos y Transformers).

cfg  = mejor_global["config"]
algo = mejor_global["algoritmo"]
ng   = int(cfg.ng)
sw   = int(cfg.sw)
st   = int(cfg.st)
mn   = int(cfg.min_df)
tf   = int(cfg.tfidf)
key  = (ng, sw, st, mn, tf)

print(f"\n{'='*60}")
print(f"EVALUACIÓN FINAL — {algo} — Split genuino 70/15/15")
print(f"Config: ng={ng} sw={sw} st={st} min_df={mn} tfidf={tf}")
print(f"Modelo entrenado en {len(X_train)} instancias (train 70%)")
print(f"Evaluado en         {len(X_test)} instancias (test 15%)")
print("="*60)

# Recuperar modelo entrenado en train; re-entrenar solo si no está en memoria
# (puede ocurrir si Colab se reinició entre celdas)
if key in modelos_guardados:
    res_mejor = modelos_guardados[key]
    print("✅ Modelo recuperado de memoria (sin re-entrenamiento)")
else:
    print("⚠️  Modelo no encontrado en memoria (sesión reiniciada).")
    print("   Re-entrenando sobre train (70%) con la mejor configuración...")
    res_mejor = entrenar_y_evaluar_val(ng, sw, st, mn, tf)
    print("   Re-entrenamiento completado sobre train (70%) únicamente.")

modelo_final = res_mejor[algo]["model"]
vect_final   = res_mejor[algo]["vect"]
scaler_final = res_mejor[algo]["scaler"]

# ── Búsqueda de umbral óptimo en validación ───────────────────
# Alineado con Transformers: umbral se selecciona en val, nunca en test
mejor_t, mejor_f1_val = buscar_umbral_optimo(modelo_final, vect_final,
                                              scaler_final, algo)
print(f"Umbral óptimo seleccionado en validación: {mejor_t:.2f} "
      f"(F1 Macro val={mejor_f1_val:.4f})")

# ── Predicciones finales sobre test con umbral óptimo ─────────
X_test_vec = vect_final.transform(X_test)
if algo == "SVM":
    X_test_vec = scaler_final.transform(X_test_vec)

proba_test  = modelo_final.predict_proba(X_test_vec)[:, 1]
predictions = (proba_test >= mejor_t).astype(int)

# ── Métricas finales ──────────────────────────────────────────
cm       = confusion_matrix(y_test, predictions)
acc      = accuracy_score(y_test, predictions)
prec     = precision_score(y_test, predictions, average="macro", zero_division=1)
rec      = recall_score(y_test, predictions, average="macro")
f1       = f1_score(y_test, predictions, average="macro")
prec_pos = precision_score(y_test, predictions, pos_label=1, average="binary")
rec_pos  = recall_score(y_test, predictions, pos_label=1, average="binary")
f1_pos   = f1_score(y_test, predictions, pos_label=1, average="binary")
f1_neg   = f1_score(y_test, predictions, pos_label=0, average="binary")

tiempo = round((time.time() - inicio) / 60, 2)

print("\n" + "="*60)
print(f"RESULTADO FINAL — {algo} (test 15%, sin re-entrenamiento)")
print("="*60)
print(classification_report(
    y_test, predictions,
    target_names=["No hace lugar (0)", "Hace lugar (1)"],
    digits=4
))
print(f"Exactitud:                {acc:.4f}")
print(f"Precisión Macro:          {prec:.4f}")
print(f"Exhaustividad Macro:      {rec:.4f}")
print(f"F1 Macro:                 {f1:.4f}")
print(f"F1 Clase Positiva:        {f1_pos:.4f}")
print(f"F1 Clase Negativa:        {f1_neg:.4f}")
print(f"Precisión Clase Positiva: {prec_pos:.4f}")
print(f"Exhaust. Clase Positiva:  {rec_pos:.4f}")
print(f"Umbral de decisión:       {mejor_t:.2f}")
print(f"F1 Macro en validación:   {mejor_f1_val:.4f}")
print(f"Tiempo total:             {tiempo} min")
print("="*60)

# ── Guardar predicciones para Bootstrap / McNemar ─────────────
np.save(os.path.join(OUTPUT_DIR, f"y_true_CLASICO_70_15_15_{algo}.npy"), y_test.values)
np.save(os.path.join(OUTPUT_DIR, f"y_pred_CLASICO_70_15_15_{algo}.npy"), predictions)
print("✅ Predicciones guardadas (.npy) para Bootstrap / McNemar")

# ── 9. MATRIZ DE CONFUSIÓN ────────────────────────────────────
etiquetas = ["No hace lugar (0)", "Hace lugar (1)"]
fig, ax   = plt.subplots(figsize=(6, 5))
im        = ax.imshow(cm, interpolation="nearest", cmap="Blues")
plt.colorbar(im, ax=ax)
ax.set(
    xticks=[0, 1], yticks=[0, 1],
    xticklabels=etiquetas, yticklabels=etiquetas,
    ylabel="Etiqueta real", xlabel="Etiqueta predicha",
    title=f"Matriz de Confusión — {algo}\nSplit 70/15/15 · sin re-entrenamiento"
)
total = cm.sum()
for i in range(2):
    for j in range(2):
        valor = cm[i, j]
        color = "white" if valor > cm.max() / 2 else "black"
        ax.text(j, i, f"{valor}\n({valor/total*100:.1f}%)",
                ha="center", va="center",
                fontsize=12, color=color, fontweight="bold")
plt.xticks(rotation=15, ha="right")
plt.tight_layout()

PNG_PATH = os.path.join(OUTPUT_DIR, f"confusion_matrix_CLASICO_70_15_15_{algo}.png")
plt.savefig(PNG_PATH, dpi=150, bbox_inches="tight")
plt.show()
print(f"\n✅ PNG guardado: {PNG_PATH}")

# ── 10. GUARDAR JSON ──────────────────────────────────────────
config_json = {
    "experimento": {
        "id":          "CLASICO-64CONFIG-70-15-15-SIN-REENTRENAMIENTO",
        "fecha":       datetime.now().strftime("%Y-%m-%d %H:%M"),
        "responsable": "Fatima Ferreira - Blanca Franco",
        "descripcion": (
            "Búsqueda exhaustiva de 64 configuraciones sobre algoritmos clásicos. "
            "Split genuino 70/15/15 estratificado (seed=42), idéntico al de los Transformers. "
            "Selección de mejor configuración por F1 Macro en validación (15%). "
            "El modelo entrenado en train (70%) se evalúa directamente en test (15%) "
            "SIN re-entrenamiento, garantizando comparación simétrica con Transformers. "
            "class_weight=balanced en LR/RF/SVM y class_prior uniforme en NB, "
            "alineado con compute_class_weight de los Transformers (desbalanceo 80/20). "
            "Umbral de decisión optimizado sobre validación, alineado con Transformers."
        ),
    },
    "decisiones_metodologicas": {
        "sin_reentrenamiento": (
            "El modelo final es el entrenado en train (70%). "
            "Esto garantiza que clásicos y Transformers compiten con exactamente "
            "la misma cantidad de datos de entrenamiento."
        ),
        "class_weight": (
            "class_weight='balanced' en LR, RF, SVM; class_prior=[0.5,0.5] en NB. "
            "Alineado con compute_class_weight('balanced') de los experimentos Transformer "
            "para compensar el desbalanceo 80/20 del corpus PyCrim."
        ),
        "umbral_decision": (
            "Búsqueda de umbral óptimo (0.20-0.80, paso 0.01) sobre validación. "
            "Alineado con el procedimiento de los experimentos Transformer."
        ),
    },
    "busqueda": {
        "total_configuraciones": 64,
        "criterio_seleccion":    "F1 Macro en conjunto de validación (15%)",
        "archivo_resultados":    "resultados_val_70_15_15.csv",
    },
    "mejor_configuracion": {
        "algoritmo":           algo,
        "ngram_range":         ng,
        "stop_words":          "Con" if sw == 1 else "Sin",
        "stemming":            "Con" if st == 1 else "Sin",
        "min_df":              mn,
        "vectorizador":        "TF-IDF" if tf == 1 else "TF (CountVectorizer)",
        "f1_macro_validacion": round(mejor_global["f1_val"], 4),
    },
    "datos": {
        "dataset":         "PyCrim",
        "archivo":         "corpusJurisprudence.txt",
        "zenodo":          "https://zenodo.org/records/14373749",
        "split_train":     0.70,
        "split_val":       0.15,
        "split_test":      0.15,
        "split_estrategia": "estratificado",
        "random_state":    SEMILLA,
        "total_muestras":  len(data),
        "train_muestras":  len(X_train),
        "val_muestras":    len(X_val),
        "test_muestras":   len(X_test),
        "entrenamiento_final": "train únicamente (70%) — sin re-entrenamiento",
        "balance_clases_test": {
            "clase_0_n":   int((y_test == 0).sum()),
            "clase_1_n":   int((y_test == 1).sum()),
            "clase_0_pct": round((y_test == 0).sum() / len(y_test) * 100, 2),
            "clase_1_pct": round((y_test == 1).sum() / len(y_test) * 100, 2),
        },
    },
    "resultados": {
        "tiempo_minutos":               tiempo,
        "umbral_decision":              mejor_t,
        "f1_macro_val_umbral":          mejor_f1_val,
        "test": {
            "exactitud":                    round(acc,      4),
            "f1_macro":                     round(f1,       4),
            "f1_clase_positiva":            round(f1_pos,   4),
            "f1_clase_negativa":            round(f1_neg,   4),
            "precision_macro":              round(prec,     4),
            "exhaustividad_macro":          round(rec,      4),
            "precision_clase_positiva":     round(prec_pos, 4),
            "exhaustividad_clase_positiva": round(rec_pos,  4),
        },
        "matriz_confusion": {
            "TP": int(cm[1, 1]),
            "TN": int(cm[0, 0]),
            "FP": int(cm[0, 1]),
            "FN": int(cm[1, 0]),
        },
    },
}

JSON_PATH = os.path.join(OUTPUT_DIR, f"config_CLASICO_70_15_15_{algo}.json")
with open(JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(config_json, f, ensure_ascii=False, indent=2)
print(f"✅ JSON guardado: {JSON_PATH}")