# -*- coding: utf-8 -*-
"""Analisis_estadistico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Va5ERFvaDMC6nmgAYgLk7IyBhPeTGJdW

# Análisis Estadístico — Bootstrap + McNemar
**Proyecto:** Predicción de Sentencias Penales — PyCrim
**Dataset:** PyCrim — Sala Penal, Corte Suprema de Justicia del Paraguay
**Responsable:** Fátima Ferreira - Blanca Franco
**Fecha:** 2026

---
### Descripción:
- Bootstrap con 10.000 iteraciones para IC 95% sobre F1 Macro de cada modelo
- Test de McNemar para comparación estadística entre SVM y BETO
- Modelos comparados: SVM (mejor clásico) vs BETO con fine-tuning (mejor Transformer)
- Predicciones cargadas desde archivos .npy generados en experimentos previos
'''

## 1. INSTALACIÓN E IMPORTS
"""

import numpy as np
from scipy.stats import chi2
from statsmodels.stats.contingency_tables import mcnemar
import json
import os
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

"""## 2. MONTAR DRIVE Y CONFIGURACIÓN"""

from google.colab import drive
drive.mount('/content/drive')

# ── Rutas ─────────────────────────────────────────────────────
DIR_CLASICO = "/content/drive/MyDrive/Proyecto/PyCrim_experiments/CLASICOS"
DIR_BETO = "/content/drive/MyDrive/Proyecto/PyCrim_experiments/EXP-0018"
OUTPUT_DIR  = "/content/drive/MyDrive/Proyecto/PyCrim_experiments/ESTADISTICO"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ── Parámetros ────────────────────────────────────────────────
N_BOOTSTRAP = 10_000
SEMILLA     = 42
CONFIANZA   = 0.95

print(f"✅ Configuración lista")
print(f"   Bootstrap: {N_BOOTSTRAP} iteraciones")
print(f"   IC: {CONFIANZA*100:.0f}%")
print(f"   Output: {OUTPUT_DIR}")

"""## 3. CARGAR PREDICCIONES"""

# ══════════════════════════════════════════════════════════════
# CELDA 4 — CARGAR PREDICCIONES
# ══════════════════════════════════════════════════════════════
print("Cargando predicciones...")

# SVM
y_true_svm = np.load(os.path.join(DIR_CLASICO, "y_true_CLASICO_SVM_final.npy"))
y_pred_svm = np.load(os.path.join(DIR_CLASICO, "y_pred_CLASICO_SVM_final.npy"))

# BETO
# BETO
y_true_beto = np.load(os.path.join(DIR_BETO, "y_true_BETO_con_fine_tuning.npy"))
y_pred_beto = np.load(os.path.join(DIR_BETO, "y_pred_BETO_con_fine_tuning.npy"))

# Verificar que los y_true son idénticos (mismo conjunto de prueba)
assert np.array_equal(y_true_svm, y_true_beto), \
    "❌ ERROR: y_true de SVM y BETO no son idénticos. Verificar que usan el mismo split."

print(f"✅ SVM  — y_true: {y_true_svm.shape} | y_pred: {y_pred_svm.shape}")
print(f"✅ BETO — y_true: {y_true_beto.shape} | y_pred: {y_pred_beto.shape}")
print(f"✅ Conjuntos de prueba idénticos verificados")
print(f"\nDistribución clases en test:")
print(f"  Clase 0 (No hace lugar): {(y_true_svm == 0).sum()} ({(y_true_svm == 0).mean()*100:.1f}%)")
print(f"  Clase 1 (Hace lugar):    {(y_true_svm == 1).sum()} ({(y_true_svm == 1).mean()*100:.1f}%)")

# ══════════════════════════════════════════════════════════════
# CELDA DIAGNÓSTICO — comparar y_true de ambos modelos
# ══════════════════════════════════════════════════════════════
print(f"Tamaño y_true SVM:  {len(y_true_svm)}")
print(f"Tamaño y_true BETO: {len(y_true_beto)}")
print(f"\nDistribución SVM:")
print(f"  Clase 0: {(y_true_svm == 0).sum()}")
print(f"  Clase 1: {(y_true_svm == 1).sum()}")
print(f"\nDistribución BETO:")
print(f"  Clase 0: {(y_true_beto == 0).sum()}")
print(f"  Clase 1: {(y_true_beto == 1).sum()}")
print(f"\nPrimeros 10 valores SVM:  {y_true_svm[:10]}")
print(f"Primeros 10 valores BETO: {y_true_beto[:10]}")

# ══════════════════════════════════════════════════════════════
# CELDA DIAGNÓSTICO 3 — verificar si es permutación
# ══════════════════════════════════════════════════════════════

# Verificar si tienen los mismos valores aunque en distinto orden
print(f"¿Mismos valores ordenados?: {np.array_equal(np.sort(y_true_svm), np.sort(y_true_beto))}")
print(f"Suma SVM:  {y_true_svm.sum()}")
print(f"Suma BETO: {y_true_beto.sum()}")

# Verificar cuántas posiciones difieren
diferencias = np.sum(y_true_svm != y_true_beto)
print(f"\nPosiciones donde y_true difiere: {diferencias} de {len(y_true_svm)}")
print(f"Porcentaje de diferencia: {diferencias/len(y_true_svm)*100:.1f}%")

"""
## 4. FUNCIÓN F1 MACRO
"""

# ══════════════════════════════════════════════════════════════
# CELDA 5 — FUNCIÓN F1 MACRO
# ══════════════════════════════════════════════════════════════
def f1_macro(y_true, y_pred):
    """
    Calcula F1 Macro implementado con NumPy puro.
    Implementación propia para uso dentro del Bootstrap
    sin overhead de sklearn en cada iteración.
    """
    clases = np.unique(y_true)
    f1s = []
    for c in clases:
        tp = np.sum((y_pred == c) & (y_true == c))
        fp = np.sum((y_pred == c) & (y_true != c))
        fn = np.sum((y_pred != c) & (y_true == c))
        prec = tp / (tp + fp) if (tp + fp) > 0 else 0
        rec  = tp / (tp + fn) if (tp + fn) > 0 else 0
        f1   = 2 * prec * rec / (prec + rec) if (prec + rec) > 0 else 0
        f1s.append(f1)
    return np.mean(f1s)

# Verificar contra valores conocidos
f1_svm_obs  = f1_macro(y_true_svm,  y_pred_svm)
f1_beto_obs = f1_macro(y_true_beto, y_pred_beto)

print(f"F1 Macro observado — SVM:  {f1_svm_obs:.4f} ({f1_svm_obs*100:.2f}%)")
print(f"F1 Macro observado — BETO: {f1_beto_obs:.4f} ({f1_beto_obs*100:.2f}%)")
print(f"Diferencia observada:      {(f1_beto_obs - f1_svm_obs):.4f} ({(f1_beto_obs - f1_svm_obs)*100:.2f} pp)")

"""
## 5. BOOTSTRAP"""

# IC 95% sobre F1 Macro de cada modelo + diferencia

print(f"{'='*60}")
print(f"BOOTSTRAP — {N_BOOTSTRAP} iteraciones | IC {CONFIANZA*100:.0f}%")
print(f"{'='*60}\n")

np.random.seed(SEMILLA)
n = len(y_true_svm)

f1_boot_svm  = np.zeros(N_BOOTSTRAP)
f1_boot_beto = np.zeros(N_BOOTSTRAP)
diff_boot    = np.zeros(N_BOOTSTRAP)

for i in range(N_BOOTSTRAP):
    idx = np.random.choice(n, size=n, replace=True)
    f1_s = f1_macro(y_true_svm[idx],  y_pred_svm[idx])
    f1_b = f1_macro(y_true_beto[idx], y_pred_beto[idx])
    f1_boot_svm[i]  = f1_s
    f1_boot_beto[i] = f1_b
    diff_boot[i]    = f1_b - f1_s

    if (i + 1) % 2000 == 0:
        print(f"  {i+1}/{N_BOOTSTRAP} iteraciones completadas...")

# ── Intervalos de confianza percentil ────────────────────────
alpha = 1 - CONFIANZA

ic_svm_low   = np.percentile(f1_boot_svm,  alpha/2 * 100)
ic_svm_high  = np.percentile(f1_boot_svm,  (1-alpha/2) * 100)
ic_beto_low  = np.percentile(f1_boot_beto, alpha/2 * 100)
ic_beto_high = np.percentile(f1_boot_beto, (1-alpha/2) * 100)
ic_diff_low  = np.percentile(diff_boot,    alpha/2 * 100)
ic_diff_high = np.percentile(diff_boot,    (1-alpha/2) * 100)

# ── p-value Bootstrap ─────────────────────────────────────────
# H0: no hay diferencia entre modelos
# p = proporción de iteraciones donde diff <= 0
# Corrección: sumar 1 al numerador y denominador (Davison & Hinkley 1997)
p_value_boot = (np.sum(diff_boot <= 0) + 1) / (N_BOOTSTRAP + 1)

print(f"\n{'='*60}")
print(f"RESULTADOS BOOTSTRAP")
print(f"{'='*60}")
print(f"\nSVM:")
print(f"  F1 Macro observado: {f1_svm_obs*100:.2f}%")
print(f"  IC 95%:             [{ic_svm_low*100:.2f}%, {ic_svm_high*100:.2f}%]")
print(f"\nBETO:")
print(f"  F1 Macro observado: {f1_beto_obs*100:.2f}%")
print(f"  IC 95%:             [{ic_beto_low*100:.2f}%, {ic_beto_high*100:.2f}%]")
print(f"\nDiferencia (BETO - SVM):")
print(f"  Observada:          {(f1_beto_obs-f1_svm_obs)*100:.2f} pp")
print(f"  IC 95%:             [{ic_diff_low*100:.2f} pp, {ic_diff_high*100:.2f} pp]")
print(f"  p-value Bootstrap:  {p_value_boot:.4f}")

if ic_diff_low > 0:
    print(f"\n✅ La diferencia es estadísticamente significativa (IC no incluye 0)")
else:
    print(f"\n⚠️  La diferencia NO es estadísticamente significativa (IC incluye 0)")

"""## 6. TEST DE McNEMAR"""

# ══════════════════════════════════════════════════════════════
# Comparación SVM vs BETO sobre el mismo conjunto de prueba
# ══════════════════════════════════════════════════════════════
print(f"{'='*60}")
print(f"TEST DE McNEMAR — SVM vs BETO")
print(f"{'='*60}\n")

# Tabla de contingencia McNemar
# b = SVM correcto, BETO incorrecto
# c = SVM incorrecto, BETO correcto
svm_correct  = (y_pred_svm  == y_true_svm)
beto_correct = (y_pred_beto == y_true_beto)

a = np.sum( svm_correct &  beto_correct)   # ambos correctos
b = np.sum( svm_correct & ~beto_correct)   # SVM correcto, BETO incorrecto
c = np.sum(~svm_correct &  beto_correct)   # SVM incorrecto, BETO correcto
d = np.sum(~svm_correct & ~beto_correct)   # ambos incorrectos

tabla_mcnemar = np.array([[a, b], [c, d]])

print(f"Tabla de contingencia McNemar:")
print(f"                    BETO correcto   BETO incorrecto")
print(f"SVM correcto        {a:>12}    {b:>14}")
print(f"SVM incorrecto      {c:>12}    {d:>14}")
print(f"\nb (SVM✓ BETO✗): {b}")
print(f"c (SVM✗ BETO✓): {c}")

# Test de McNemar con corrección de continuidad
resultado_mcnemar = mcnemar(tabla_mcnemar, exact=False, correction=True)
estadistico = resultado_mcnemar.statistic
p_value_mcnemar = resultado_mcnemar.pvalue

print(f"\nEstadístico chi²: {estadistico:.4f}")
print(f"p-value:          {p_value_mcnemar:.4f}")

if p_value_mcnemar < 0.05:
    print(f"\n✅ Diferencia estadísticamente significativa (p < 0.05)")
    print(f"   BETO y SVM cometen errores significativamente distintos")
else:
    print(f"\n⚠️  Diferencia NO estadísticamente significativa (p ≥ 0.05)")
    print(f"   No hay evidencia suficiente de que los modelos difieran")

"""
##7. VISUALIZACIONES"""

fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# ── Plot 1: Distribución Bootstrap SVM ───────────────────────
axes[0].hist(f1_boot_svm * 100, bins=50, color='steelblue',
             alpha=0.7, edgecolor='white')
axes[0].axvline(f1_svm_obs * 100, color='red',
                linestyle='--', linewidth=2, label=f'Observado: {f1_svm_obs*100:.2f}%')
axes[0].axvline(ic_svm_low * 100, color='orange',
                linestyle=':', linewidth=2, label=f'IC 95%: [{ic_svm_low*100:.2f}%, {ic_svm_high*100:.2f}%]')
axes[0].axvline(ic_svm_high * 100, color='orange', linestyle=':', linewidth=2)
axes[0].set_title('Bootstrap — SVM\nDistribución F1 Macro')
axes[0].set_xlabel('F1 Macro (%)')
axes[0].set_ylabel('Frecuencia')
axes[0].legend(fontsize=8)

# ── Plot 2: Distribución Bootstrap BETO ──────────────────────
axes[1].hist(f1_boot_beto * 100, bins=50, color='seagreen',
             alpha=0.7, edgecolor='white')
axes[1].axvline(f1_beto_obs * 100, color='red',
                linestyle='--', linewidth=2, label=f'Observado: {f1_beto_obs*100:.2f}%')
axes[1].axvline(ic_beto_low * 100, color='orange',
                linestyle=':', linewidth=2, label=f'IC 95%: [{ic_beto_low*100:.2f}%, {ic_beto_high*100:.2f}%]')
axes[1].axvline(ic_beto_high * 100, color='orange', linestyle=':', linewidth=2)
axes[1].set_title('Bootstrap — BETO\nDistribución F1 Macro')
axes[1].set_xlabel('F1 Macro (%)')
axes[1].set_ylabel('Frecuencia')
axes[1].legend(fontsize=8)

# ── Plot 3: Distribución diferencia BETO - SVM ───────────────
axes[2].hist(diff_boot * 100, bins=50, color='mediumpurple',
             alpha=0.7, edgecolor='white')
axes[2].axvline((f1_beto_obs - f1_svm_obs) * 100, color='red',
                linestyle='--', linewidth=2,
                label=f'Observada: {(f1_beto_obs-f1_svm_obs)*100:.2f} pp')
axes[2].axvline(ic_diff_low * 100, color='orange',
                linestyle=':', linewidth=2,
                label=f'IC 95%: [{ic_diff_low*100:.2f}, {ic_diff_high*100:.2f}] pp')
axes[2].axvline(ic_diff_high * 100, color='orange', linestyle=':', linewidth=2)
axes[2].axvline(0, color='black', linestyle='-', linewidth=1, alpha=0.5)
axes[2].set_title('Bootstrap — Diferencia\nBETO - SVM (F1 Macro)')
axes[2].set_xlabel('Diferencia (pp)')
axes[2].set_ylabel('Frecuencia')
axes[2].legend(fontsize=8)

plt.tight_layout()
fig_path = os.path.join(OUTPUT_DIR, "bootstrap_mcnemar_visualizacion.png")
plt.savefig(fig_path, dpi=300, bbox_inches='tight')
plt.show()
print(f"✅ Figura guardada: {fig_path}")

"""## 8. GUARDAR RESULTADOS JSON"""

resultados = {
    "experimento": {
        "fecha":        datetime.now().strftime("%Y-%m-%d %H:%M"),
        "n_bootstrap":  N_BOOTSTRAP,
        "confianza":    CONFIANZA,
        "semilla":      SEMILLA,
        "n_test":       int(n),
        "modelos":      ["SVM", "BETO con fine-tuning"],
    },
    "bootstrap": {
        "SVM": {
            "f1_macro_observado": round(float(f1_svm_obs),  4),
            "ic_95_low":          round(float(ic_svm_low),  4),
            "ic_95_high":         round(float(ic_svm_high), 4),
        },
        "BETO": {
            "f1_macro_observado": round(float(f1_beto_obs),  4),
            "ic_95_low":          round(float(ic_beto_low),  4),
            "ic_95_high":         round(float(ic_beto_high), 4),
        },
        "diferencia_BETO_minus_SVM": {
            "observada_pp":  round(float(f1_beto_obs - f1_svm_obs) * 100, 2),
            "ic_95_low_pp":  round(float(ic_diff_low)  * 100, 2),
            "ic_95_high_pp": round(float(ic_diff_high) * 100, 2),
            "p_value":       round(float(p_value_boot), 4),
            "significativo": bool(ic_diff_low > 0),
        },
    },
    "mcnemar": {
        "tabla_contingencia": {
            "a_ambos_correctos":       int(a),
            "b_svm_correcto_beto_no":  int(b),
            "c_beto_correcto_svm_no":  int(c),
            "d_ambos_incorrectos":     int(d),
        },
        "estadistico_chi2": round(float(estadistico),      4),
        "p_value":          round(float(p_value_mcnemar),  4),
        "significativo":    bool(p_value_mcnemar < 0.05),
        "correccion_continuidad": True,
    },
}

JSON_PATH = os.path.join(OUTPUT_DIR, "bootstrap_mcnemar_resultados.json")
with open(JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(resultados, f, ensure_ascii=False, indent=2)

print(f"✅ Resultados guardados: {JSON_PATH}")

# ── Resumen final ─────────────────────────────────────────────
print(f"\n{'='*60}")
print(f"RESUMEN FINAL")
print(f"{'='*60}")
print(f"\nBootstrap ({N_BOOTSTRAP} iteraciones, IC 95%):")
print(f"  SVM:  {f1_svm_obs*100:.2f}% [{ic_svm_low*100:.2f}%, {ic_svm_high*100:.2f}%]")
print(f"  BETO: {f1_beto_obs*100:.2f}% [{ic_beto_low*100:.2f}%, {ic_beto_high*100:.2f}%]")
print(f"  Diferencia: {(f1_beto_obs-f1_svm_obs)*100:.2f} pp [{ic_diff_low*100:.2f}, {ic_diff_high*100:.2f}] pp")
print(f"  p-value Bootstrap: {p_value_boot:.4f}")
print(f"\nMcNemar (corrección continuidad):")
print(f"  chi²={estadistico:.4f} | p-value={p_value_mcnemar:.4f}")
print(f"\nConclusión:")
if ic_diff_low > 0 and p_value_mcnemar < 0.05:
    print(f"  ✅ BETO supera a SVM de forma estadísticamente significativa")
elif ic_diff_low > 0 or p_value_mcnemar < 0.05:
    print(f"  ⚠️  Evidencia mixta — revisar ambas pruebas")
else:
    print(f"  ⚠️  La diferencia NO es estadísticamente significativa")