# -*- coding: utf-8 -*-
"""analisis_interpretabilidad_ultimo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186v7yPymO59E8-IndTw-IXc_wauFrPgz

# Análisis Shap
**Proyecto:** Predicción de Sentencias Penales — PyCrim
**Dataset:** PyCrim — Sala Penal, Corte Suprema de Justicia del Paraguay
**Responsable:** Fátima Ferreira - Blanca Franco
**Fecha:** 2026

---
### Descripción:

## 1.INSTALACIÓN
"""

import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"
!pip install shap -q

import shap
import pickle
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from sklearn.metrics import confusion_matrix
from google.colab import drive

print("✅ Instalación completa")

"""##2.MONTAR DRIVE Y CONFIGURACIÓN"""

drive.mount('/content/drive')

OUTPUT_DIR  = "/content/drive/MyDrive/Proyecto/PyCrim_experiments"
DIR_CLASICO = f"{OUTPUT_DIR}/CLASICOS"
DIR_BETO    = f"{OUTPUT_DIR}/EXP-0018"
MODELS_DIR  = f"{DIR_CLASICO}/modelos_pkl"
SHAP_DIR    = f"{OUTPUT_DIR}/SHAP"

import os
os.makedirs(SHAP_DIR, exist_ok=True)

print("✅ Configuración lista")

# ══════════════════════════════════════════════════════════════
# CELDA 2b — DEFINIR FUNCIONES DE PREPROCESAMIENTO
# Necesarias para cargar el modelo SVM desde .pkl
# ══════════════════════════════════════════════════════════════
import nltk
from nltk.stem import SnowballStemmer
from nltk.corpus import stopwords

nltk.download("punkt",     quiet=True)
nltk.download("punkt_tab", quiet=True)
nltk.download("stopwords", quiet=True)

stemmer           = SnowballStemmer("spanish")
spanish_stopwords = stopwords.words("spanish")

def tokenize_and_stem_stop(text):
    tokens = nltk.word_tokenize(text.lower())
    tokens = [w for w in tokens if w not in spanish_stopwords]
    return [stemmer.stem(t) for t in tokens]

print("✅ Funciones de preprocesamiento definidas")

"""## 3.CARGAR MODELO SVM Y PREDICCIONES"""

with open(f"{MODELS_DIR}/modelo_SVM.pkl", "rb") as f:
    obj = pickle.load(f)

modelo_svm = obj["model"]
vect_svm   = obj["vect"]
scaler_svm = obj["scaler"]
umbral_svm = 0.595  # tomado del JSON resultados_CLASICOS_4algo_70_15_15fin

print(f"✅ Modelo SVM cargado | umbral={umbral_svm}")

# Cargar predicciones
y_true = np.load(f"{DIR_CLASICO}/y_true_CLASICO_SVM_final.npy")
y_pred_svm = np.load(f"{DIR_CLASICO}/y_pred_CLASICO_SVM_final.npy")

# Cargar textos
with open(f"{DIR_BETO}/test_texts.json", "r", encoding="utf-8") as f:
    test_texts = json.load(f)

print(f"✅ Predicciones cargadas: {len(y_true)} instancias")
print(f"✅ Textos cargados: {len(test_texts)} documentos")

"""## 4.SELECCIONAR 20 CASOS REPRESENTATIVOS"""

# 5 TP, 5 TN, 5 FP, 5 FN
# ══════════════════════════════════════════════════════════════
np.random.seed(42)

# Identificar cada tipo de caso
idx_TP = np.where((y_true == 1) & (y_pred_svm == 1))[0]
idx_TN = np.where((y_true == 0) & (y_pred_svm == 0))[0]
idx_FP = np.where((y_true == 0) & (y_pred_svm == 1))[0]
idx_FN = np.where((y_true == 1) & (y_pred_svm == 0))[0]

print(f"Disponibles — TP: {len(idx_TP)} | TN: {len(idx_TN)} | FP: {len(idx_FP)} | FN: {len(idx_FN)}")

# Seleccionar 5 de cada tipo
n = 5
sel_TP = np.random.choice(idx_TP, size=min(n, len(idx_TP)), replace=False)
sel_TN = np.random.choice(idx_TN, size=min(n, len(idx_TN)), replace=False)
sel_FP = np.random.choice(idx_FP, size=min(n, len(idx_FP)), replace=False)
sel_FN = np.random.choice(idx_FN, size=min(n, len(idx_FN)), replace=False)

casos = {
    "TP": sel_TP,
    "TN": sel_TN,
    "FP": sel_FP,
    "FN": sel_FN
}

print(f"\nCasos seleccionados:")
for tipo, idx in casos.items():
    print(f"  {tipo}: índices {idx}")

"""## 5.SHAP SOBRE SVM"""

# ══════════════════════════════════════════════════════════════
# CELDA 5 — SHAP SOBRE SVM (versión optimizada memoria)
# ══════════════════════════════════════════════════════════════

# Índices de todos los casos seleccionados
todos_idx = np.concatenate([sel_TP, sel_TN, sel_FP, sel_FN])

# Vectorizar SOLO los 20 casos seleccionados
X_casos_vec    = vect_svm.transform([test_texts[i] for i in todos_idx])
X_casos_scaled = scaler_svm.transform(X_casos_vec)

# Usar solo features con varianza > 0 en los 20 casos
# Esto reduce enormemente el número de features
X_casos_dense = X_casos_scaled.toarray()
mask_nonzero  = X_casos_dense.sum(axis=0) > 0
X_casos_red   = X_casos_dense[:, mask_nonzero]
feature_names_red = np.array(vect_svm.get_feature_names_out())[mask_nonzero]

print(f"Features originales: {X_casos_dense.shape[1]}")
print(f"Features reducidos (no cero): {X_casos_red.shape[1]}")

# Coeficientes del SVM lineal reducidos
# Convertir a array denso primero para evitar error de indexado
coef_full = np.array(modelo_svm.coef_.todense()).flatten()
coef_red  = coef_full[mask_nonzero]
intercept = modelo_svm.intercept_[0]

# SHAP manual para SVM lineal
# Para SVM lineal: shap_value_i = coef_i * x_i
# Es equivalente a LinearExplainer pero sin overhead de memoria
shap_values = X_casos_red * coef_red

print(f"✅ SHAP values calculados: shape={shap_values.shape}")
print(f"✅ Features: {len(feature_names_red)} tokens activos")

"""## 6.ANÁLISIS CUALITATIVO POR CASO"""

# ══════════════════════════════════════════════════════════════
# Top tokens positivos y negativos para cada caso
# ══════════════════════════════════════════════════════════════

def analizar_caso(shap_vals, feature_names, idx_global, tipo, top_n=10):
    """Muestra los top tokens que más influyeron en la predicción."""
    sv = shap_vals
    top_pos_idx = np.argsort(sv)[-top_n:][::-1]
    top_neg_idx = np.argsort(sv)[:top_n]

    print(f"\n{'='*60}")
    print(f"Caso {tipo} — índice test: {idx_global}")
    print(f"{'='*60}")
    print(f"Top {top_n} tokens → POSITIVO (hacen lugar):")
    for i in top_pos_idx:
        if sv[i] > 0:
            print(f"  {feature_names[i]:40s} SHAP={sv[i]:+.4f}")
    print(f"\nTop {top_n} tokens → NEGATIVO (no hacen lugar):")
    for i in top_neg_idx:
        if sv[i] < 0:
            print(f"  {feature_names[i]:40s} SHAP={sv[i]:+.4f}")

# Analizar cada caso
offset = 0
for tipo, indices in casos.items():
    for j, idx_global in enumerate(indices):
        analizar_caso(
            shap_values[offset + j],
            feature_names_red,
            idx_global,
            tipo
        )
    offset += len(indices)

"""##7.VISUALIZACIÓN GLOBAL"""

# Top 20 tokens más importantes globalmente
# ══════════════════════════════════════════════════════════════

# Importancia global = media del valor absoluto de SHAP
mean_abs_shap = np.abs(shap_values).mean(axis=0)
top20_idx     = np.argsort(mean_abs_shap)[-20:][::-1]

fig, ax = plt.subplots(figsize=(10, 7))
ax.barh(
    range(20),
    mean_abs_shap[top20_idx][::-1],
    color='steelblue', alpha=0.8
)
ax.set_yticks(range(20))
ax.set_yticklabels(feature_names_red[top20_idx][::-1], fontsize=9)
ax.set_xlabel('Importancia SHAP media (|valor|)')
ax.set_title('Top 20 tokens más importantes — SVM\n(sobre 20 casos representativos)')
plt.tight_layout()
plt.savefig(f"{SHAP_DIR}/shap_svm_top20_tokens.png", dpi=300, bbox_inches='tight')
plt.show()
print(f"✅ Figura guardada")

"""##8.GUARDAR RESULTADOS JSON"""

# ══════════════════════════════════════════════════════════════

# ══════════════════════════════════════════════════════════════
from datetime import datetime

resultados_shap = {
    "experimento": {
        "fecha":   datetime.now().strftime("%Y-%m-%d %H:%M"),
        "modelo":  "SVM",
        "n_casos": 20,
        "distribucion": {"TP": 5, "TN": 5, "FP": 5, "FN": 5}
    },
    "casos": {}
}

offset = 0
for tipo, indices in casos.items():
    resultados_shap["casos"][tipo] = []
    for j, idx_global in enumerate(indices):
        sv = shap_values[offset + j]
        top5_pos = [
            {"token": feature_names_red[i], "shap": round(float(sv[i]), 4)}
            for i in np.argsort(sv)[-5:][::-1] if sv[i] > 0
        ]
        top5_neg = [
            {"token": feature_names_red[i], "shap": round(float(sv[i]), 4)}
            for i in np.argsort(sv)[:5] if sv[i] < 0
        ]
        resultados_shap["casos"][tipo].append({
            "idx_test":  int(idx_global),
            "top5_pos":  top5_pos,
            "top5_neg":  top5_neg
        })
    offset += len(indices)

JSON_PATH = f"{SHAP_DIR}/shap_svm_resultados.json"
with open(JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(resultados_shap, f, ensure_ascii=False, indent=2)

print(f"✅ Resultados SHAP guardados: {JSON_PATH}")

import os
DIR_BETO = "/content/drive/MyDrive/Proyecto/PyCrim_experiments/EXP-0018"
for archivo in os.listdir(DIR_BETO):
    print(archivo)

import json

with open("/content/drive/MyDrive/Proyecto/PyCrim_experiments/EXP-018/config_BETO_con_fine_tuning.json") as f:
    config = json.load(f)

print("Learning rate:", config.get("learning_rate") or config.get("hiperparametros", {}).get("learning_rate"))
print("F1 macro test:", config.get("resultados", {}).get("test", {}).get("f1_macro"))
print("Umbral:", config.get("resultados", {}).get("umbral_decision"))

# ══════════════════════════════════════════════════════════════
# CELDA — ATTENTION WEIGHTS BETO
# ══════════════════════════════════════════════════════════════
!pip install transformers -q

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

# ── Cargar modelo y tokenizador ───────────────────────────────
CHECKPOINT_PATH = "/content/drive/MyDrive/Proyecto/PyCrim_experiments/EXP-00018/best_model_final"

print("⚙️  Cargando modelo BETO...")
tokenizer = AutoTokenizer.from_pretrained("dccuchile/bert-base-spanish-wwm-cased")
model     = AutoModelForSequenceClassification.from_pretrained(
    CHECKPOINT_PATH,
    output_attentions=True
)
model.eval()
print("✅ Modelo cargado")

import torch
import numpy as np
import re

# ── Fix 1: Agrupar subpalabras ────────────────────────────────
def agrupar_subpalabras(tokens, attentions):
    palabras    = []
    atenciones  = []
    palabra_actual  = ""
    atencion_actual = 0.0

    for tok, att in zip(tokens, attentions):
        if tok in ["[CLS]", "[SEP]", "[PAD]"]:
            continue
        if tok.startswith("##"):
            palabra_actual  += tok[2:]
            atencion_actual += att
        else:
            if palabra_actual:
                palabras.append(palabra_actual)
                atenciones.append(atencion_actual)
            palabra_actual  = tok
            atencion_actual = float(att)

    if palabra_actual:
        palabras.append(palabra_actual)
        atenciones.append(atencion_actual)

    return palabras, atenciones


# ── Fix 2: Filtrar tokens poco informativos ───────────────────
TOKENS_IGNORAR = {
    "[CLS]", "[SEP]", "[PAD]",
    ",", ".", "-", ":", ";", ")", "(", "\"", "'", "/",
    "el", "la", "los", "las", "de", "del", "en", "y",
    "a", "que", "con", "por", "un", "una", "su", "se",
    "al", "lo", "le", "les", "es", "no", "si", "ya",
    "o", "e", "u", "ni"
}

def es_informativo(token):
    if token.lower() in TOKENS_IGNORAR:
        return False
    if re.match(r'^\d+$', token):   # solo números
        return False
    if len(token) <= 1:              # letras sueltas
        return False
    return True


# ── Fix 3: Función principal con sliding window ───────────────
def get_attention_weights_v2(text, tokenizer, model,
                              max_length=512, stride=384, top_n=10):
    """
    Calcula attention weights con:
    - Sliding window para documentos largos
    - Agrupación de subpalabras
    - Filtrado de tokens poco informativos
    """
    tokens_full = tokenizer.encode(text, add_special_tokens=False)
    n_tokens    = len(tokens_full)

    # ── Documento corto: procesar directo ─────────────────────
    if n_tokens <= max_length - 2:
        inputs = tokenizer(
            text, return_tensors="pt",
            max_length=max_length,
            truncation=True, padding=False
        )
        with torch.no_grad():
            outputs = model(**inputs)

        logits   = outputs.logits
        proba    = torch.softmax(logits, dim=-1).numpy()[0]
        pred     = int(np.argmax(proba))

        last_layer    = outputs.attentions[-1]
        avg_heads     = last_layer[0].mean(dim=0)
        cls_attention = avg_heads[0].numpy()

        tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
        palabras, atenciones = agrupar_subpalabras(tokens, cls_attention)

        scores = [
            (tok, att) for tok, att in zip(palabras, atenciones)
            if es_informativo(tok)
        ]
        scores_sorted = sorted(scores, key=lambda x: x[1], reverse=True)[:top_n]

        return {
            "top_tokens": scores_sorted,
            "pred":       pred,
            "proba_pos":  float(proba[1]),
            "n_tokens":   n_tokens,
            "n_palabras": len(text.split()),
            "n_fragmentos": 1
        }

    # ── Documento largo: sliding window ───────────────────────
    # Predicción: usar primer fragmento (contiene el encabezado)
    primer_frag = tokens_full[:max_length - 2]
    input_ids   = [tokenizer.cls_token_id] + primer_frag + [tokenizer.sep_token_id]
    input_tensor = torch.tensor([input_ids])

    with torch.no_grad():
        outputs_pred = model(input_tensor)

    logits = outputs_pred.logits
    proba  = torch.softmax(logits, dim=-1).numpy()[0]
    pred   = int(np.argmax(proba))

    # Atención: promediar sobre todos los fragmentos
    acumulado = {}  # palabra -> lista de atenciones

    n_fragmentos = 0
    for start in range(0, n_tokens, stride):
        end        = min(start + max_length - 2, n_tokens)
        frag_ids   = tokens_full[start:end]
        input_ids  = [tokenizer.cls_token_id] + frag_ids + [tokenizer.sep_token_id]
        tensor     = torch.tensor([input_ids])

        with torch.no_grad():
            out = model(tensor)

        last_layer    = out.attentions[-1]
        avg_heads     = last_layer[0].mean(dim=0)
        cls_attention = avg_heads[0].numpy()

        tokens_frag = tokenizer.convert_ids_to_tokens(input_ids)
        palabras, atenciones = agrupar_subpalabras(tokens_frag, cls_attention)

        for tok, att in zip(palabras, atenciones):
            if es_informativo(tok):
                if tok not in acumulado:
                    acumulado[tok] = []
                acumulado[tok].append(att)

        n_fragmentos += 1
        if end == n_tokens:
            break

    # Promediar atenciones por token
    atencion_promedio = {
        tok: float(np.mean(atts))
        for tok, atts in acumulado.items()
    }

    scores_sorted = sorted(
        atencion_promedio.items(),
        key=lambda x: x[1], reverse=True
    )[:top_n]

    return {
        "top_tokens":   scores_sorted,
        "pred":         pred,
        "proba_pos":    float(proba[1]),
        "n_tokens":     n_tokens,
        "n_palabras":   len(text.split()),
        "n_fragmentos": n_fragmentos
    }

# ── Selección de casos basada en predicciones de BETO ────────
y_pred_beto = np.load(f"{DIR_BETO}/y_pred_BETO_con_fine_tuning.npy")
y_true_beto = np.load(f"{DIR_BETO}/y_true_BETO_con_fine_tuning.npy")

np.random.seed(42)

idx_TP_beto = np.where((y_true_beto == 1) & (y_pred_beto == 1))[0]
idx_TN_beto = np.where((y_true_beto == 0) & (y_pred_beto == 0))[0]
idx_FP_beto = np.where((y_true_beto == 0) & (y_pred_beto == 1))[0]
idx_FN_beto = np.where((y_true_beto == 1) & (y_pred_beto == 0))[0]

n = 5
casos_beto = {
    "TP": np.random.choice(idx_TP_beto, size=min(n, len(idx_TP_beto)), replace=False),
    "TN": np.random.choice(idx_TN_beto, size=min(n, len(idx_TN_beto)), replace=False),
    "FP": np.random.choice(idx_FP_beto, size=min(n, len(idx_FP_beto)), replace=False),
    "FN": np.random.choice(idx_FN_beto, size=min(n, len(idx_FN_beto)), replace=False),
}

print(f"Casos BETO — TP:{len(idx_TP_beto)} TN:{len(idx_TN_beto)} FP:{len(idx_FP_beto)} FN:{len(idx_FN_beto)}")
for tipo, idx in casos_beto.items():
    print(f"  {tipo}: {idx}")

# ── Análisis sobre los 20 casos ───────────────────────────────
resultados_beto = {}

for tipo, indices in casos_beto.items():
    resultados_beto[tipo] = []
    for idx_global in indices:
        texto  = test_texts[idx_global]
        result = get_attention_weights_v2(texto, tokenizer, model)

        print(f"\n{'='*60}")
        print(f"Caso {tipo} — índice test: {idx_global}")
        print(f"{'='*60}")
        print(f"Predicción BETO: {'Hace lugar (1)' if result['pred']==1 else 'No hace lugar (0)'}")
        print(f"Probabilidad positiva: {result['proba_pos']*100:.2f}%")
        print(f"Palabras totales: {result['n_palabras']} | "
              f"Fragmentos procesados: {result['n_fragmentos']}")
        print(f"\nTop 10 tokens con mayor atención:")
        for tok, att in result["top_tokens"]:
            print(f"  {tok:35s} att={att:.4f}")

        resultados_beto[tipo].append({
            "idx_test":     int(idx_global),
            "pred":         result["pred"],
            "proba_pos":    round(result["proba_pos"], 4),
            "n_fragmentos": result["n_fragmentos"],
            "top_tokens":   [(t, round(a, 4)) for t, a in result["top_tokens"]]
        })

print("\n✅ Análisis BETO completado")

# ══════════════════════════════════════════════════════════════
# VISUALIZACIÓN GLOBAL — BETO
# Top 20 tokens más importantes sobre los 20 casos
# ══════════════════════════════════════════════════════════════

# Acumular todas las atenciones de los 20 casos
acumulado_global = {}

for tipo, casos_lista in resultados_beto.items():
    for caso in casos_lista:
        for tok, att in caso["top_tokens"]:
            if tok not in acumulado_global:
                acumulado_global[tok] = []
            acumulado_global[tok].append(att)

# Promediar por token
importancia_global = {
    tok: float(np.mean(atts))
    for tok, atts in acumulado_global.items()
}

# Top 20
top20 = sorted(importancia_global.items(), key=lambda x: x[1], reverse=True)[:20]
tokens_top20  = [t for t, _ in top20][::-1]
valores_top20 = [v for _, v in top20][::-1]

# ── Gráfico ───────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(10, 7))
ax.barh(range(20), valores_top20, color='steelblue', alpha=0.8)
ax.set_yticks(range(20))
ax.set_yticklabels(tokens_top20, fontsize=9)
ax.set_xlabel('Importancia media de atención')
ax.set_title('Top 20 tokens más importantes — BETO\n(sobre 20 casos representativos)')
plt.tight_layout()
plt.savefig(f"{SHAP_DIR}/attention_beto_top20_tokens.png", dpi=300, bbox_inches='tight')
plt.show()
print("✅ Figura guardada")

# ── Guardar JSON ──────────────────────────────────────────────
from datetime import datetime
import json, os

resultados_attention = {
    "experimento": {
        "fecha":        datetime.now().strftime("%Y-%m-%d %H:%M"),
        "modelo":       "BETO fine-tuning",
        "checkpoint":   "best_model_final",
        "metodo":       (
            "attention weights — última capa, promedio cabezas, token CLS. "
            "Sliding window 512/384 para documentos largos. "
            "Subpalabras agrupadas. Tokens no informativos filtrados."
        ),
        "n_casos":      20,
        "distribucion": {"TP": 5, "TN": 5, "FP": 5, "FN": 5}
    },
    "casos": resultados_beto
}

JSON_PATH = os.path.join(SHAP_DIR, "attention_weights_beto.json")
with open(JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(resultados_attention, f, ensure_ascii=False, indent=2)

print(f"✅ JSON guardado: {JSON_PATH}")