# -*- coding: utf-8 -*-
"""clasicos_64config_validacion_explicita (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKd1AtWVC9O7RMz4ZpRmZXzYwweyo5MV
"""

# ══════════════════════════════════════════════════════════════
# BÚSQUEDA EXHAUSTIVA — 64 CONFIGURACIONES — ALGORITMOS CLÁSICOS
# Split 70/15/15 estratificado con validación explícita
# Alineado con protocolo de experimentos Transformer
#
# Flujo correcto:
#   1. Las 64 configuraciones se evalúan sobre VALIDACIÓN
#   2. Se elige la mejor configuración por F1 Macro en validación
#   3. Se evalúa UNA SOLA VEZ sobre el conjunto de prueba
#   4. Ese resultado final es el que se reporta
# ══════════════════════════════════════════════════════════════

import zipfile
import io
import json
import time
import os
import pandas as pd
import nltk
from datetime import datetime
from itertools import product
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, classification_report, confusion_matrix
)

# ── 1. MONTAR DRIVE ───────────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

# ── 2. CONFIGURACIÓN ──────────────────────────────────────────
ZIP_PATH    = "/content/drive/MyDrive/PyCrim_dataset.zip"
ZIP_ARCHIVO = "corpusJurisprudence.txt"
OUTPUT_DIR  = "/content/drive/MyDrive/Proyecto/PyCrim_experiments/CLASICOS"
os.makedirs(OUTPUT_DIR, exist_ok=True)

SEMILLA = 42   # alineado con experimentos Transformer

# Columnas del dataset — igual que template Transformer
COLUMNA_TEXTO = "Contenido Txt"
COLUMNA_LABEL = "Resultado binario de la acción"

inicio = time.time()

# ── 3. CARGAR DATASET ─────────────────────────────────────────
with zipfile.ZipFile(ZIP_PATH, "r") as zipref:
    datos = io.BytesIO(zipref.read(ZIP_ARCHIVO))

data = pd.read_csv(datos, sep="\t")
print(f"Dataset cargado: {data.shape}")
print("\nDistribución de clases (dataset completo):")
print(data[COLUMNA_LABEL].value_counts())
print(data[COLUMNA_LABEL].value_counts(normalize=True).round(3))

# ── 4. SPLIT 70/15/15 ESTRATIFICADO ───────────────────────────
# Replicando EXACTAMENTE el mismo proceso que los experimentos Transformer
# para garantizar que train/val/test contienen las mismas instancias

# Paso 1: separar 70% train del 30% restante (val+test)
train_df, temp_df = train_test_split(
    data, test_size=0.30,
    stratify=data[COLUMNA_LABEL],
    random_state=SEMILLA
)

# Paso 2: dividir el 30% en 15% val y 15% test
val_df, test_df = train_test_split(
    temp_df, test_size=0.50,
    stratify=temp_df[COLUMNA_LABEL],
    random_state=SEMILLA
)

X_train = train_df[COLUMNA_TEXTO]
y_train = train_df[COLUMNA_LABEL]
X_val   = val_df[COLUMNA_TEXTO]
y_val   = val_df[COLUMNA_LABEL]
X_test  = test_df[COLUMNA_TEXTO]
y_test  = test_df[COLUMNA_LABEL]

print(f"\nTrain: {len(X_train)} ({len(X_train)/len(data)*100:.1f}%)")
print(f"Val:   {len(X_val)}  ({len(X_val)/len(data)*100:.1f}%)")
print(f"Test:  {len(X_test)}  ({len(X_test)/len(data)*100:.1f}%)")

print("\nDistribución clases en train:")
print(y_train.value_counts(normalize=True).round(3))
print("Distribución clases en val:")
print(y_val.value_counts(normalize=True).round(3))
print("Distribución clases en test:")
print(y_test.value_counts(normalize=True).round(3))

# ── 5. PREPROCESAMIENTO ───────────────────────────────────────
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

stemmer = SnowballStemmer("spanish")
spanish_stopwords = stopwords.words("spanish")

def stem_tokens(tokens):
    return [stemmer.stem(token) for token in tokens]

def tokenize_and_stem(text):
    tokens = nltk.word_tokenize(text.lower())
    return stem_tokens(tokens)

def tokenize_and_stem_stop(text):
    tokens = nltk.word_tokenize(text.lower())
    tokens = [w for w in tokens if w not in spanish_stopwords]
    return stem_tokens(tokens)

# ── 6. BÚSQUEDA EXHAUSTIVA — 64 CONFIGURACIONES ───────────────
# Evaluación sobre VALIDACIÓN para seleccionar la mejor config

def vectorizar_y_evaluar(X_tr, X_ev, y_tr, y_ev,
                         param0, param1, param2, param3, param4):
    """
    Entrena sobre X_tr/y_tr y evalúa sobre X_ev/y_ev.
    Durante la búsqueda: X_ev=X_val, y_ev=y_val
    Durante evaluación final: X_ev=X_test, y_ev=y_test

    param0: ngramas (1,2,3,4)
    param1: stopwords (0=sin, 1=con)
    param2: stemming  (0=sin, 1=con)
    param3: min_df    (2, 3)
    param4: vectorizador (0=TF, 1=TF-IDF)
    """
    token_pattern_var = r"(?u)\b\w+\b"
    stop_word_var     = None
    tokenizer_var     = None

    if param1 == 0 and param2 == 0:
        pass  # sin sw, sin stemming
    elif param1 == 1 and param2 == 0:
        stop_word_var = spanish_stopwords
    elif param1 == 0 and param2 == 1:
        tokenizer_var     = tokenize_and_stem
        token_pattern_var = None
    else:
        tokenizer_var     = tokenize_and_stem_stop
        token_pattern_var = None

    params_vect = {
        "ngram_range":    (param0, param0),
        "stop_words":     stop_word_var,
        "tokenizer":      tokenizer_var,
        "token_pattern":  token_pattern_var,
        "min_df":         param3,
    }

    vect = CountVectorizer(**params_vect) if param4 == 0 else TfidfVectorizer(**params_vect)
    X_tr_vec = vect.fit_transform(X_tr)
    X_ev_vec = vect.transform(X_ev)

    resultados = {}

    def metricas(y_ev, preds):
        return {
            "acc":  round(accuracy_score(y_ev, preds), 4),
            "prec": round(precision_score(y_ev, preds, average="macro", zero_division=1), 4),
            "rec":  round(recall_score(y_ev, preds, average="macro"), 4),
            "f1":   round(f1_score(y_ev, preds, average="macro"), 4),
        }

    # Naive Bayes
    class_counts = pd.Series(y_tr).value_counts()
    class_prior  = (class_counts / class_counts.sum()).tolist()
    nb = MultinomialNB(alpha=0.1, class_prior=class_prior)
    nb.fit(X_tr_vec, y_tr)
    resultados["NB"] = {"model": nb, "vect": vect,
                        **metricas(y_ev, nb.predict(X_ev_vec))}

    # Logistic Regression
    lr = LogisticRegression(max_iter=2000, random_state=SEMILLA)
    lr.fit(X_tr_vec, y_tr)
    resultados["LR"] = {"model": lr, "vect": vect,
                        **metricas(y_ev, lr.predict(X_ev_vec))}

    # Random Forest
    rf = RandomForestClassifier(n_estimators=100, random_state=SEMILLA)
    rf.fit(X_tr_vec, y_tr)
    resultados["RF"] = {"model": rf, "vect": vect,
                        **metricas(y_ev, rf.predict(X_ev_vec))}

    # SVM
    scaler       = StandardScaler(with_mean=False)
    X_tr_scaled  = scaler.fit_transform(X_tr_vec)
    X_ev_scaled  = scaler.transform(X_ev_vec)
    svm = SVC(kernel="linear", max_iter=-1, random_state=SEMILLA)
    svm.fit(X_tr_scaled, y_tr)
    resultados["SVM"] = {"model": svm, "vect": vect, "scaler": scaler,
                         **metricas(y_ev, svm.predict(X_ev_scaled))}

    return resultados


# Generar las 64 combinaciones
combinaciones = list(product([1,2,3,4], [0,1], [0,1], [2,3], [0,1]))
print(f"Total de configuraciones a evaluar: {len(combinaciones)}")

# Archivo de checkpoint para no perder progreso si Colab se desconecta
CHECKPOINT_FILE = os.path.join(OUTPUT_DIR, "resultados_validacion_64config.csv")

if os.path.exists(CHECKPOINT_FILE):
    df_resultados = pd.read_csv(CHECKPOINT_FILE)
    print(f"Checkpoint encontrado: {len(df_resultados)} configuraciones ya procesadas")
else:
    df_resultados = pd.DataFrame(columns=[
        "ng", "sw", "st", "min_df", "tfidf",
        "NB_acc",  "NB_prec",  "NB_rec",  "NB_f1",
        "LR_acc",  "LR_prec",  "LR_rec",  "LR_f1",
        "RF_acc",  "RF_prec",  "RF_rec",  "RF_f1",
        "SVM_acc", "SVM_prec", "SVM_rec", "SVM_f1",
    ])

# Iterar sobre las 64 combinaciones evaluando sobre VALIDACIÓN
for i, (ng, sw, st, mn, tf) in enumerate(combinaciones):
    ya_calculado = (
        (df_resultados["ng"]     == ng) &
        (df_resultados["sw"]     == sw) &
        (df_resultados["st"]     == st) &
        (df_resultados["min_df"] == mn) &
        (df_resultados["tfidf"]  == tf)
    ).any()

    if not ya_calculado:
        # Evaluar sobre VALIDACIÓN
        res = vectorizar_y_evaluar(
            X_train, X_val, y_train, y_val,
            ng, sw, st, mn, tf
        )
        nuevo = pd.DataFrame([[
            ng, sw, st, mn, tf,
            res["NB"]["acc"],  res["NB"]["prec"],  res["NB"]["rec"],  res["NB"]["f1"],
            res["LR"]["acc"],  res["LR"]["prec"],  res["LR"]["rec"],  res["LR"]["f1"],
            res["RF"]["acc"],  res["RF"]["prec"],  res["RF"]["rec"],  res["RF"]["f1"],
            res["SVM"]["acc"], res["SVM"]["prec"], res["SVM"]["rec"], res["SVM"]["f1"],
        ]], columns=df_resultados.columns)

        df_resultados = pd.concat([df_resultados, nuevo], ignore_index=True)
        df_resultados.to_csv(CHECKPOINT_FILE, index=False)

        if (i + 1) % 8 == 0:
            print(f"  {i+1}/64 configuraciones procesadas...")

print("\n✅ Búsqueda exhaustiva completada")
print(df_resultados.to_string(index=False))

# ── 7. SELECCIONAR MEJOR CONFIGURACIÓN POR VALIDACIÓN ─────────

algoritmos = ["NB", "LR", "RF", "SVM"]
mejor_global = {"algoritmo": None, "config": None, "f1_val": -1}

print("Mejor configuración por algoritmo (F1 Macro en VALIDACIÓN):")
print("-" * 65)

for algo in algoritmos:
    col  = f"{algo}_f1"
    idx  = df_resultados[col].idxmax()
    fila = df_resultados.loc[idx]
    print(f"{algo:4s} → ng={int(fila.ng)} sw={int(fila.sw)} "
          f"st={int(fila.st)} min_df={int(fila.min_df)} "
          f"tfidf={int(fila.tfidf)}  F1_val={fila[col]:.4f}")

    if fila[col] > mejor_global["f1_val"]:
        mejor_global = {
            "algoritmo": algo,
            "config":    fila,
            "f1_val":    fila[col]
        }

print("-" * 65)
print(f"\nMEJOR GLOBAL en validación: {mejor_global['algoritmo']} "
      f"con F1 Macro = {mejor_global['f1_val']:.4f}")

# ── 8. EVALUACIÓN FINAL SOBRE PRUEBA ──────────────────────────
# Se re-entrena con train+val y se evalúa UNA SOLA VEZ sobre test

import matplotlib
import matplotlib.pyplot as plt
matplotlib.use('Agg')

mejor_config = mejor_global["config"]
ng = int(mejor_config.ng)
sw = int(mejor_config.sw)
st = int(mejor_config.st)
mn = int(mejor_config.min_df)
tf = int(mejor_config.tfidf)
algo = mejor_global["algoritmo"]

# Combinar train + val para el entrenamiento final
import pandas as pd
X_train_final = pd.concat([X_train, X_val])
y_train_final = pd.concat([y_train, y_val])
print(f"Entrenamiento final: {len(X_train_final)} instancias (train + val)")
print(f"Evaluación final sobre: {len(X_test)} instancias de prueba")
print(f"Configuración seleccionada: algoritmo={algo} ng={ng} "
      f"sw={sw} st={st} min_df={mn} tfidf={tf}")

# Re-entrenar con la mejor configuración sobre train+val
res_final = vectorizar_y_evaluar(
    X_train_final, X_test, y_train_final, y_test,
    ng, sw, st, mn, tf
)

# Obtener predicciones del mejor algoritmo para métricas completas
mejor_modelo = res_final[algo]["model"]
mejor_vect   = res_final[algo]["vect"]

X_train_vec = mejor_vect.fit_transform(X_train_final)
X_test_vec  = mejor_vect.transform(X_test)

if algo == "SVM":
    scaler      = res_final[algo]["scaler"]
    X_train_vec = scaler.fit_transform(X_train_vec)
    X_test_vec  = scaler.transform(X_test_vec)

mejor_modelo.fit(X_train_vec, y_train_final)
predictions = mejor_modelo.predict(X_test_vec)

# Métricas finales
cm       = confusion_matrix(y_test, predictions)
acc      = accuracy_score(y_test, predictions)
prec     = precision_score(y_test, predictions, average="macro", zero_division=1)
rec      = recall_score(y_test, predictions, average="macro")
f1       = f1_score(y_test, predictions, average="macro")
prec_pos = precision_score(y_test, predictions, pos_label=1, average="binary")
rec_pos  = recall_score(y_test, predictions, pos_label=1, average="binary")
f1_pos   = f1_score(y_test, predictions, pos_label=1, average="binary")
f1_neg   = f1_score(y_test, predictions, pos_label=0, average="binary")

tiempo = round((time.time() - inicio) / 60, 2)

print("\n" + "="*60)
print(f"RESULTADO FINAL — {algo} (evaluado sobre conjunto de prueba)")
print("="*60)
print(classification_report(
    y_test, predictions,
    target_names=["No hace lugar (0)", "Hace lugar (1)"],
    digits=4
))
print(f"Exactitud:               {acc:.4f}")
print(f"Precisión Macro:         {prec:.4f}")
print(f"Exhaustividad Macro:     {rec:.4f}")
print(f"F1 Macro:                {f1:.4f}")
print(f"F1 Clase Positiva:       {f1_pos:.4f}")
print(f"F1 Clase Negativa:       {f1_neg:.4f}")
print(f"Precisión Clase Positiva:{prec_pos:.4f}")
print(f"Exhaust. Clase Positiva: {rec_pos:.4f}")
print(f"Tiempo total:            {tiempo} min")
print("="*60)

# ── 9. MATRIZ DE CONFUSIÓN ────────────────────────────────────
etiquetas = ["No hace lugar (0)", "Hace lugar (1)"]
fig, ax = plt.subplots(figsize=(6, 5))
im = ax.imshow(cm, interpolation="nearest", cmap="Blues")
plt.colorbar(im, ax=ax)
ax.set(
    xticks=[0, 1], yticks=[0, 1],
    xticklabels=etiquetas, yticklabels=etiquetas,
    ylabel="Etiqueta real", xlabel="Etiqueta predicha",
    title=f"Matriz de Confusión\n{algo} — Split 70/15/15 estratificado"
)
total = cm.sum()
for i in range(2):
    for j in range(2):
        valor = cm[i, j]
        color = "white" if valor > cm.max() / 2 else "black"
        ax.text(j, i, f"{valor}\n({valor/total*100:.1f}%)",
                ha="center", va="center",
                fontsize=12, color=color, fontweight="bold")
plt.xticks(rotation=15, ha="right")
plt.tight_layout()

PNG_PATH = os.path.join(OUTPUT_DIR, f"confusion_matrix_{algo}_70_15_15.png")
plt.savefig(PNG_PATH, dpi=150, bbox_inches="tight")
plt.show()
print(f"\n✅ PNG guardado en: {PNG_PATH}")

# ── 10. GUARDAR JSON ──────────────────────────────────────────
config_json = {
    "experimento": {
        "id": f"CLASICO-64CONFIG-VALIDACION-EXPLICITA",
        "fecha": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "responsable": "Fatima Ferreira - Blanca Franco",
        "descripcion": (
            "Búsqueda exhaustiva de 64 configuraciones sobre algoritmos clásicos. "
            "Selección de mejor configuración por F1 Macro en validación. "
            "Evaluación final una sola vez sobre conjunto de prueba. "
            "Split 70/15/15 estratificado con random_state=42, "
            "alineado con protocolo de experimentos Transformer."
        )
    },
    "busqueda": {
        "total_configuraciones": 64,
        "criterio_seleccion": "F1 Macro en conjunto de validacion",
        "archivo_resultados_validacion": "resultados_validacion_64config.csv"
    },
    "mejor_configuracion": {
        "algoritmo": algo,
        "ngram_range": ng,
        "stop_words": "Con" if sw == 1 else "Sin",
        "stemming": "Con" if st == 1 else "Sin",
        "min_df": mn,
        "vectorizador": "TF-IDF" if tf == 1 else "TF (CountVectorizer)",
        "f1_macro_validacion": round(mejor_global["f1_val"], 4)
    },
    "datos": {
        "dataset": "PyCrim",
        "archivo": "corpusJurisprudence.txt",
        "zenodo": "https://zenodo.org/records/14373749",
        "split_train": 0.70,
        "split_val":   0.15,
        "split_test":  0.15,
        "split_estrategia": "estratificado",
        "random_state": SEMILLA,
        "total_muestras":  len(data),
        "train_muestras":  len(X_train),
        "val_muestras":    len(X_val),
        "test_muestras":   len(X_test),
        "entrenamiento_final": "train + val combinados",
        "balance_clases_test": {
            "clase_0_n":   int((y_test == 0).sum()),
            "clase_1_n":   int((y_test == 1).sum()),
            "clase_0_pct": round((y_test == 0).sum() / len(y_test) * 100, 2),
            "clase_1_pct": round((y_test == 1).sum() / len(y_test) * 100, 2)
        }
    },
    "resultados": {
        "tiempo_minutos": tiempo,
        "test": {
            "exactitud":                    round(acc,      4),
            "f1_macro":                     round(f1,       4),
            "f1_clase_positiva":            round(f1_pos,   4),
            "f1_clase_negativa":            round(f1_neg,   4),
            "precision_macro":              round(prec,     4),
            "exhaustividad_macro":          round(rec,      4),
            "precision_clase_positiva":     round(prec_pos, 4),
            "exhaustividad_clase_positiva": round(rec_pos,  4)
        },
        "matriz_confusion": {
            "TP": int(cm[1, 1]),
            "TN": int(cm[0, 0]),
            "FP": int(cm[0, 1]),
            "FN": int(cm[1, 0])
        }
    }
}

JSON_PATH = os.path.join(OUTPUT_DIR, f"config_{algo}_64config_validacion_explicita.json")
with open(JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(config_json, f, ensure_ascii=False, indent=2)
print(f"✅ JSON guardado en: {JSON_PATH}")

# ── 11. SUBIR A GITHUB ────────────────────────────────────────
import os, shutil, subprocess

commit_msg = f"Clásicos 64 config — validación explícita 70/15/15 — mejor: {algo}"

with open("/content/drive/MyDrive/Proyecto/github_token.txt") as f:
    token = f.read().strip()

GITHUB_USER = "blanqui-franco"
GITHUB_REPO = "pycrim-transformers"
REPO_PATH   = f"/content/{GITHUB_REPO}"
REPO_URL    = f"https://{GITHUB_USER}:{token}@github.com/{GITHUB_USER}/{GITHUB_REPO}.git"

if not os.path.exists(REPO_PATH):
    subprocess.run(["git", "clone", REPO_URL, REPO_PATH], check=True)
    print("✅ Repo clonado")
else:
    subprocess.run(["git", "-C", REPO_PATH, "pull"], check=True)
    print("✅ Repo actualizado")

subprocess.run(["git", "-C", REPO_PATH, "config", "user.email", "blanquisaldivar9@gmail.com"], check=True)
subprocess.run(["git", "-C", REPO_PATH, "config", "user.name",  "blanqui-franco"], check=True)

carpeta_destino = os.path.join(REPO_PATH, "experiments", "CLASICOS")
os.makedirs(carpeta_destino, exist_ok=True)

# Copiar JSON, PNG y CSV de resultados de validación
shutil.copy(JSON_PATH,       carpeta_destino)
shutil.copy(PNG_PATH,        carpeta_destino)
shutil.copy(CHECKPOINT_FILE, carpeta_destino)
print("✅ JSON, PNG y CSV copiados al repo local")

subprocess.run(["git", "-C", REPO_PATH, "add", "experiments/CLASICOS/"], check=True)

result_commit = subprocess.run(
    ["git", "-C", REPO_PATH, "commit", "-m", commit_msg],
    capture_output=True, text=True
)
print(result_commit.stdout)

if result_commit.returncode == 0:
    subprocess.run(["git", "-C", REPO_PATH, "push", REPO_URL, "main"], check=True)
    print(f"✅ Resultados subidos a GitHub — {commit_msg}")
else:
    print("⚠️ Nada nuevo para commitear")