# -*- coding: utf-8 -*-
"""EXP019_longformer_legal_spanish.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jzc9voANG1e9S-dRCXmw6nzc-nBf_dPU

# Experimento: LegalLongformer-ES — [MODALIDAD]

**Proyecto:** Aplicación de modelos Transformers para la clasificación de casos judiciales — PyCrim  
**Dataset:** PyCrim — Sala Penal, Corte Suprema de Justicia del Paraguay  
**Responsable:** Fatima Ferreira - Blanca Franco  
**Fecha:** 30/05/2026

---
### Diferencias respecto al template BETO/mBERT/XLM-RoBERTa:
1. Modelo: `Narrativa/legal-longformer-base-4096-spanish` (RoBERTa-based, legal español)
2. `MAX_LENGTH = 4096` → procesa el documento completo **sin sliding window**
3. `STRIDE` no aplica — se mantiene en config por compatibilidad con logger pero no se usa
4. Longformer requiere `attention_mask` con valores 0/1/2 (global attention en [CLS])
5. `global_attention_mask`: valor 1 en posición [CLS] (token 0), 0 en el resto
6. `AutoModelForSequenceClassification` es compatible con Longformer via HuggingFace

### Antes de correr este notebook:
1. Cambiar `MODALIDAD` en la celda de configuración
2. Seleccionar **GPU A100** en Entorno de ejecución (Longformer 4096 requiere ~18-24 GB VRAM)
3. Montar Google Drive (se hace automáticamente en la celda 5)

## 0. Instalación de dependencias
"""

!pip install transformers datasets scikit-learn torch --quiet

"""## 1. Configuración
⚠️ **SOLO TOCAR ESTA CELDA — cambiar MODALIDAD**
"""

# ══════════════════════════════════════════════════════════
# COMPLETAR ANTES DE CORRER
# ══════════════════════════════════════════════════════════
EXP_ID      = "EXP-021"                    # EXP-019 = LegalLongformer sin FT | EXP-020 = con FT
MODELO      = "LegalLongformer-ES"         # identificador interno
MODALIDAD   = "sin_fine_tuning"            # "sin_fine_tuning" | "con_fine_tuning"
RESPONSABLE = "Fatima Ferreira - Blanca Franco"

# ══════════════════════════════════════════════════════════
# NO MODIFICAR — hiperparámetros fijos para reproducibilidad
# ══════════════════════════════════════════════════════════
SEMILLA       = 42
MAX_LENGTH    = 4096   # Longformer soporta hasta 4096 tokens — procesa doc completo
STRIDE        = None   # No aplica para Longformer — se deja None por compatibilidad con logger
LEARNING_RATE = 5e-6   # Protocolo optimizado — igual que BETO/XLM-RoBERTa
EPOCHS        = 7
BATCH_SIZE    = 2      # Reducido por VRAM: 4096 tokens × 2 = ~8192 tokens/batch
GRAD_ACCUM    = 8      # Effective batch size = 2 × 8 = 16 (igual que template original)

# Rutas — mismas que el template original
ZIP_PATH    = "/content/drive/MyDrive/PyCrim_dataset.zip"
ZIP_ARCHIVO = "corpusJurisprudence.txt"
OUTPUT_DIR  = "/content/drive/MyDrive/Proyecto/PyCrim_experiments"

# Columnas del dataset — sin cambios
COLUMNA_TEXTO = "Contenido Txt"
COLUMNA_LABEL = "Resultado binario de la acción"

# Modelo HuggingFace
MODEL_NAME = "Narrativa/legal-longformer-base-4096-spanish"

print(f"Experimento: {EXP_ID}")
print(f"Modelo:      {MODELO} → {MODEL_NAME}")
print(f"Modalidad:   {MODALIDAD}")
print(f"MAX_LENGTH:  {MAX_LENGTH} tokens (documento completo, sin sliding window)")
print(f"Batch size efectivo: {BATCH_SIZE} × {GRAD_ACCUM} = {BATCH_SIZE * GRAD_ACCUM}")
print(f"Semilla:     {SEMILLA}")

"""## 2. Semilla fija — SIEMPRE antes de cualquier otra cosa"""

import random, os
import numpy as np
import torch

def set_seed(seed=42):
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    print(f"✓ Semilla fijada: {seed}")
    print(f"✓ GPU disponible: {torch.cuda.is_available()}")
    if torch.cuda.is_available():
        print(f"✓ GPU: {torch.cuda.get_device_name(0)}")
        vram = torch.cuda.get_device_properties(0).total_memory / 1e9
        print(f"✓ VRAM total: {vram:.1f} GB")

set_seed(SEMILLA)

"""## 3. Imports"""

import zipfile, io, json, time, platform
from datetime import datetime
from collections import defaultdict

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, precision_recall_fscore_support,
    f1_score, precision_score, recall_score,
    classification_report, confusion_matrix
)

from transformers import (
    AutoTokenizer, AutoModel,
    AutoModelForSequenceClassification,
    TrainingArguments, Trainer, EarlyStoppingCallback
)
from datasets import Dataset
from google.colab import drive

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"✓ Imports OK | Device: {device}")

"""## 4. Logger automático de experimentos"""

class ExperimentLogger:
    """Guarda automáticamente config + resultados en JSON al terminar."""

    def __init__(self, exp_id, modelo, modalidad, responsable,
                 semilla, epochs, batch_size, learning_rate,
                 max_length, stride, output_dir):
        self.exp_id     = exp_id
        self.modelo     = modelo
        self.modalidad  = modalidad
        self.output_dir = output_dir
        self.inicio     = time.time()

        import sys, transformers as tr
        gpu = torch.cuda.get_device_name(0) if torch.cuda.is_available() else "no disponible"
        try:
            import google.colab
            plataforma = "Google Colab"
        except ImportError:
            plataforma = f"local ({platform.system()})"

        self.config = {
            "experimento": {
                "id": exp_id,
                "fecha": datetime.now().strftime("%Y-%m-%d %H:%M"),
                "responsable": responsable,
                "descripcion": f"{modelo} {modalidad.replace('_',' ')} — semilla {semilla}",
                "semilla": semilla,
            },
            "modelo": {
                "nombre": modelo,
                "nombre_huggingface": MODEL_NAME,
                "modalidad": modalidad,
                "num_labels": 2,
                "arquitectura_base": "RoBERTa (via RoBERTalex)",
                "max_tokens_soportados": 4096,
                "atencion": "sliding_window_local + global_en_CLS",
            },
            "tokenizacion": {
                "max_length": max_length,
                "stride": "no_aplica_longformer",
                "estrategia": "documento_completo_sin_fragmentacion",
                "padding": "max_length",
                "global_attention": "token_CLS_posicion_0",
            },
            "entrenamiento": {
                "epochs": epochs,
                "batch_size_por_dispositivo": batch_size,
                "gradient_accumulation_steps": GRAD_ACCUM,
                "effective_batch_size": batch_size * GRAD_ACCUM,
                "learning_rate": learning_rate,
                "weight_decay": 0.01,
                "optimizer": "AdamW",
                "warmup_steps": 500,
                "fp16": True,
                "early_stopping_patience": 2,
                "class_weights": True,
                "aggregacion_predicciones": "promedio_probabilidades_por_documento",
            },
            "datos": {
                "dataset": "PyCrim",
                "archivo": "corpusJurisprudence.txt",
                "zenodo": "https://zenodo.org/records/14373749",
                "split_train": 0.70, "split_val": 0.15, "split_test": 0.15,
                "split_estrategia": "aleatorio_estratificado",
                "random_state": semilla,
                "total_muestras": 5000,
                "balance_clases": {"clase_0_pct": 80.94, "clase_1_pct": 19.06},
            },
            "entorno": {
                "python_version": sys.version.split()[0],
                "torch_version": torch.__version__,
                "transformers_version": tr.__version__,
                "plataforma": plataforma,
                "gpu": gpu,
            },
            "resultados": None,
        }
        print(f"\n[Logger] {exp_id} iniciado — {modelo} {modalidad}")

    def guardar_resultados(self, accuracy, f1_macro, f1_positiva, f1_negativa,
                           precision_macro, recall_macro,
                           precision_positiva=None, recall_positiva=None,
                           tp=None, tn=None, fp=None, fn=None,
                           mejor_epoch=None, tiempo_minutos=None):

        if tiempo_minutos is None:
            tiempo_minutos = round((time.time() - self.inicio) / 60, 2)

        self.config["resultados"] = {
            "tiempo_minutos": tiempo_minutos,
            "mejor_epoch": mejor_epoch,
            "test": {
                "accuracy":                 round(accuracy, 4),
                "f1_macro":                 round(f1_macro, 4),
                "f1_clase_positiva":        round(f1_positiva, 4),
                "f1_clase_negativa":        round(f1_negativa, 4),
                "precision_macro":          round(precision_macro, 4),
                "recall_macro":             round(recall_macro, 4),
                "precision_clase_positiva": round(precision_positiva, 4) if precision_positiva else None,
                "recall_clase_positiva":    round(recall_positiva, 4) if recall_positiva else None,
            },
            "matriz_confusion": {"TP": tp, "TN": tn, "FP": fp, "FN": fn},
        }

        carpeta = os.path.join(self.output_dir, self.exp_id)
        os.makedirs(carpeta, exist_ok=True)
        path = os.path.join(carpeta, f"config_{self.modelo}_{self.modalidad}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(self.config, f, ensure_ascii=False, indent=2)

        t = self.config["resultados"]["test"]
        print("\n" + "="*50)
        print(f"  {self.exp_id}: {self.modelo} ({self.modalidad})")
        print("="*50)
        print(f"  Accuracy:    {t['accuracy']:.4f}")
        print(f"  F1 Macro:    {t['f1_macro']:.4f}")
        print(f"  F1 Positiva: {t['f1_clase_positiva']:.4f}")
        print(f"  F1 Negativa: {t['f1_clase_negativa']:.4f}")
        print(f"  Tiempo:      {tiempo_minutos} min")
        print(f"  Guardado en: {path}")
        print("="*50)
        return path


# Inicializar logger
logger = ExperimentLogger(
    exp_id=EXP_ID, modelo=MODELO, modalidad=MODALIDAD,
    responsable=RESPONSABLE, semilla=SEMILLA,
    epochs=EPOCHS, batch_size=BATCH_SIZE,
    learning_rate=LEARNING_RATE,
    max_length=MAX_LENGTH, stride=STRIDE,
    output_dir=OUTPUT_DIR,
)

"""## 5. Carga de datos"""

drive.mount('/content/drive')

with zipfile.ZipFile(ZIP_PATH, 'r') as zipref:
    datos = io.BytesIO(zipref.read(ZIP_ARCHIVO))

data = pd.read_csv(datos, sep="\t")
data['doc_id'] = range(len(data))

print("=" * 60)
print("DATASET CARGADO")
print("=" * 60)
print(f"Total documentos: {len(data)}")
print("\nDistribución de clases:")
print(data[COLUMNA_LABEL].value_counts())
print(f"\nDesbalanceo: {data[COLUMNA_LABEL].value_counts(normalize=True)[0]:.2%} clase 0")

# División 70/15/15 estratificada — idéntica al template original
train_df, temp_df = train_test_split(
    data, test_size=0.30,
    stratify=data[COLUMNA_LABEL],
    random_state=SEMILLA
)
val_df, test_df = train_test_split(
    temp_df, test_size=0.50,
    stratify=temp_df[COLUMNA_LABEL],
    random_state=SEMILLA
)

print(f"\nDivisión:")
print(f"  Train: {len(train_df)} documentos")
print(f"  Val:   {len(val_df)} documentos")
print(f"  Test:  {len(test_df)} documentos")

X_train, y_train = train_df[COLUMNA_TEXTO].values, train_df[COLUMNA_LABEL].values
X_val,   y_val   = val_df[COLUMNA_TEXTO].values,   val_df[COLUMNA_LABEL].values
X_test,  y_test  = test_df[COLUMNA_TEXTO].values,  test_df[COLUMNA_LABEL].values
doc_ids_train    = train_df["doc_id"].values
doc_ids_val      = val_df["doc_id"].values
doc_ids_test     = test_df["doc_id"].values

print("\n✅ Datos preprocesados y divididos")

"""## 6. Tokenización para Longformer

> **Diferencia clave respecto al template original:**  
> Longformer procesa el documento completo (hasta 4096 tokens) sin sliding window.  
> Se agrega `global_attention_mask` con valor 1 en el token [CLS] (posición 0) para que el modelo
> aplique atención global desde esa posición — requerimiento de la arquitectura Longformer [Beltagy et al., 2020].
"""

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize_longformer(texts, labels, doc_ids):
    """
    Tokenización para Longformer: un fragmento por documento (hasta 4096 tokens).
    Agrega global_attention_mask con 1 en CLS (posición 0), 0 en el resto.
    Documentos que excedan 4096 tokens serán truncados — se reporta cuántos.
    """
    all_data = {
        "input_ids": [],
        "attention_mask": [],
        "global_attention_mask": [],
        "labels": [],
        "doc_id": []
    }
    truncados = 0

    for text, label, doc_id in zip(texts, labels, doc_ids):
        # Verificar si el doc excede 4096 tokens (solo para registro)
        tokens_raw = tokenizer(str(text), truncation=False)["input_ids"]
        if len(tokens_raw) > MAX_LENGTH:
            truncados += 1

        enc = tokenizer(
            str(text),
            padding="max_length",
            truncation=True,
            max_length=MAX_LENGTH,
            return_tensors=None
        )

        # Global attention: 1 en CLS (posición 0), 0 en el resto
        global_att = [0] * MAX_LENGTH
        global_att[0] = 1

        all_data["input_ids"].append(enc["input_ids"])
        all_data["attention_mask"].append(enc["attention_mask"])
        all_data["global_attention_mask"].append(global_att)
        all_data["labels"].append(label)
        all_data["doc_id"].append(doc_id)

    print(f"  {len(texts)} documentos tokenizados")
    print(f"  Documentos que exceden 4096 tokens (truncados): {truncados} ({truncados/len(texts)*100:.1f}%)")
    return Dataset.from_dict(all_data)


print("=" * 60)
print("TOKENIZACIÓN LONGFORMER (documento completo)")
print("=" * 60)
print(f"MAX_LENGTH={MAX_LENGTH} | Sin sliding window")
print("\nTrain:")
train_dataset = tokenize_longformer(X_train, y_train, doc_ids_train)
print("Val:")
val_dataset   = tokenize_longformer(X_val,   y_val,   doc_ids_val)
print("Test:")
test_dataset  = tokenize_longformer(X_test,  y_test,  doc_ids_test)
print("\n✅ Tokenización completada")

"""## 7. Experimento
> Si `MODALIDAD == 'sin_fine_tuning'` → extrae embeddings ([CLS] token) + Regresión Logística  
> Si `MODALIDAD == 'con_fine_tuning'` → fine-tuning completo con WeightedTrainer
>
> **Nota:** En Longformer no se necesita agregación por fragmentos porque cada documento
> es un único ejemplo. La predicción es directa sobre el documento completo.
"""

# Pesos de clase para el desbalance 80/20
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float).to(device)
print(f"Pesos de clase: {class_weights.round(3)}")


if MODALIDAD == "sin_fine_tuning":
    # ── SIN FINE-TUNING ───────────────────────────────────────
    print("\n" + "=" * 60)
    print("EXPERIMENTO: SIN FINE-TUNING")
    print("=" * 60)

    model_base = AutoModel.from_pretrained(MODEL_NAME).to(device)
    model_base.eval()

    def extract_embeddings_longformer(texts, doc_ids):
        """
        Extrae embedding del token [CLS] con atención global.
        Un forward pass por documento (sin sliding window).
        """
        embeddings = []
        for i, (text, doc_id) in enumerate(zip(texts, doc_ids)):
            enc = tokenizer(
                str(text),
                return_tensors="pt",
                max_length=MAX_LENGTH,
                truncation=True,
                padding="max_length"
            ).to(device)

            # Global attention en CLS
            global_att = torch.zeros_like(enc["attention_mask"])
            global_att[0, 0] = 1

            with torch.no_grad():
                outputs = model_base(
                    input_ids=enc["input_ids"],
                    attention_mask=enc["attention_mask"],
                    global_attention_mask=global_att
                )
            # CLS token = posición 0 del last_hidden_state
            embeddings.append(outputs.last_hidden_state[:, 0, :].cpu().numpy()[0])

            if (i + 1) % 100 == 0:
                print(f"  Procesados: {i+1}/{len(texts)}")

        return np.array(embeddings)

    print("Extrayendo embeddings Train...")
    X_train_emb = extract_embeddings_longformer(X_train, doc_ids_train)
    print("Extrayendo embeddings Test...")
    X_test_emb  = extract_embeddings_longformer(X_test,  doc_ids_test)

    print("\nEntrenando Regresión Logística...")
    clf = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=SEMILLA)
    clf.fit(X_train_emb, y_train)

    y_pred      = clf.predict(X_test_emb)
    y_true      = y_test
    mejor_epoch = None


else:
    # ── CON FINE-TUNING ───────────────────────────────────────
    print("\n" + "=" * 60)
    print("EXPERIMENTO: CON FINE-TUNING")
    print("=" * 60)

    model_ft = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=2
    )

    class WeightedTrainer(Trainer):
        def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
            labels  = inputs.pop("labels")
            outputs = model(**inputs)
            loss_fct = torch.nn.CrossEntropyLoss(weight=class_weights_tensor)
            loss     = loss_fct(outputs.logits, labels)
            return (loss, outputs) if return_outputs else loss

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=-1)
        acc   = accuracy_score(labels, preds)
        f1    = f1_score(labels, preds, average='macro')
        return {"accuracy": acc, "f1": f1}

    training_args = TrainingArguments(
        output_dir                  = f"{OUTPUT_DIR}/{EXP_ID}/checkpoints",
        save_steps                  = 100,
        eval_strategy               = "epoch",
        save_strategy               = "epoch",
        learning_rate               = LEARNING_RATE,
        per_device_train_batch_size = BATCH_SIZE,
        per_device_eval_batch_size  = 4,       # Reducido por VRAM en inferencia
        gradient_accumulation_steps = GRAD_ACCUM,
        num_train_epochs            = EPOCHS,
        weight_decay                = 0.01,
        warmup_steps                = 500,
        load_best_model_at_end      = True,
        metric_for_best_model       = "f1",    # F1-macro — protocolo optimizado
        logging_steps               = 50,
        fp16                        = True,
        save_total_limit            = 2,
        seed                        = SEMILLA,
        report_to                   = "none",
    )

    trainer = WeightedTrainer(
        model           = model_ft,
        args            = training_args,
        train_dataset   = train_dataset,
        eval_dataset    = val_dataset,
        compute_metrics = compute_metrics,
        callbacks       = [EarlyStoppingCallback(early_stopping_patience=2)]
    )

    print("\n⚡ Iniciando entrenamiento...")
    trainer.train()
    # Si se cortó, retomar desde el último checkpoint:
    # CHECKPOINT = f"{OUTPUT_DIR}/{EXP_ID}/checkpoints/checkpoint-XXXX"
    # trainer.train(resume_from_checkpoint=CHECKPOINT)

    print("\n✅ Entrenamiento completado")

    # ── BÚSQUEDA DE UMBRAL ÓPTIMO EN VAL ──────────────────────
    # Nota: sin sliding window, cada doc_id aparece exactamente una vez
    # por lo que aggregate_predictions es equivalente a predicción directa.
    # Se mantiene para simetría de protocolo con los experimentos anteriores.

    def aggregate_predictions(logits, doc_ids, labels, threshold=0.5):
        probs    = torch.softmax(torch.tensor(logits), dim=-1).numpy()
        doc_data = defaultdict(lambda: {"probs": [], "label": None})
        for prob, doc_id, label in zip(probs, doc_ids, labels):
            doc_data[doc_id]["probs"].append(prob)
            doc_data[doc_id]["label"] = label
        preds, true_labels = [], []
        for doc_id in sorted(doc_data.keys()):
            avg_prob = np.mean(doc_data[doc_id]["probs"], axis=0)
            preds.append(1 if avg_prob[1] >= threshold else 0)
            true_labels.append(doc_data[doc_id]["label"])
        return np.array(preds), np.array(true_labels)

    val_predictions = trainer.predict(val_dataset)

    # Rango 0.50–0.60 con incrementos de 0.005 — igual que protocolo optimizado
    thresholds = np.arange(0.50, 0.601, 0.005)
    resultados_umbral = []
    for t in thresholds:
        preds_val, true_val = aggregate_predictions(
            val_predictions.predictions,
            val_dataset["doc_id"],
            val_dataset["labels"],
            threshold=t
        )
        f1_val = f1_score(true_val, preds_val, average='macro')
        resultados_umbral.append((round(t, 3), round(f1_val, 4)))

    mejor_umbral, mejor_f1_val = max(resultados_umbral, key=lambda x: x[1])
    print(f"\nTop 5 umbrales por F1 macro en validación:")
    for t, f in sorted(resultados_umbral, key=lambda x: x[1], reverse=True)[:5]:
        print(f"  umbral={t:.3f} → F1 macro val={f:.4f}")
    print(f"\n✅ Umbral óptimo seleccionado: {mejor_umbral} (F1 val={mejor_f1_val:.4f})")

    # ── EVALUACIÓN FINAL EN TEST CON UMBRAL ÓPTIMO ────────────
    predictions = trainer.predict(test_dataset)
    y_pred, y_true = aggregate_predictions(
        predictions.predictions,
        test_dataset["doc_id"],
        test_dataset["labels"],
        threshold=mejor_umbral
    )
    mejor_epoch = trainer.state.best_model_checkpoint

print("\n✅ Experimento completado")

"""## 8. Evaluación y guardado automático de resultados"""

print("\n" + "=" * 60)
print("EVALUACIÓN")
print("=" * 60)

print(classification_report(y_true, y_pred, target_names=['No hace lugar', 'Hace lugar'], digits=4))

cm       = confusion_matrix(y_true, y_pred)
acc      = accuracy_score(y_true, y_pred)
f1_mac   = f1_score(y_true, y_pred, average='macro')
f1_pos   = f1_score(y_true, y_pred, pos_label=1, average='binary')
f1_neg   = f1_score(y_true, y_pred, pos_label=0, average='binary')
prec_mac = precision_score(y_true, y_pred, average='macro')
rec_mac  = recall_score(y_true, y_pred, average='macro')
prec_pos = precision_score(y_true, y_pred, pos_label=1, average='binary')
rec_pos  = recall_score(y_true, y_pred, pos_label=1, average='binary')

# Guardar JSON automáticamente
logger.guardar_resultados(
    accuracy           = acc,
    f1_macro           = f1_mac,
    f1_positiva        = f1_pos,
    f1_negativa        = f1_neg,
    precision_macro    = prec_mac,
    recall_macro       = rec_mac,
    precision_positiva = prec_pos,
    recall_positiva    = rec_pos,
    tp  = int(cm[1,1]), tn = int(cm[0,0]),
    fp  = int(cm[0,1]), fn = int(cm[1,0]),
    mejor_epoch = mejor_epoch,
)

# Guardar predicciones para Bootstrap/McNemar
np.save(f"{OUTPUT_DIR}/{EXP_ID}/y_true_{MODELO}_{MODALIDAD}.npy", y_true)
np.save(f"{OUTPUT_DIR}/{EXP_ID}/y_pred_{MODELO}_{MODALIDAD}.npy", y_pred)
print("✅ Predicciones guardadas")

"""## 9. Visualizaciones"""

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[0],
            xticklabels=['No', 'Sí'], yticklabels=['No', 'Sí'])
axes[0].set_title(f'Matriz de Confusión\n{MODELO} — {MODALIDAD}')
axes[0].set_ylabel('Verdadero')
axes[0].set_xlabel('Predicho')

metricas = {'Accuracy': acc, 'F1 Macro': f1_mac,
            'F1 Positiva': f1_pos, 'F1 Negativa': f1_neg,
            'Precision': prec_mac, 'Recall': rec_mac}
axes[1].bar(metricas.keys(), metricas.values(), color='steelblue')
axes[1].set_ylim(0, 1)
axes[1].set_title(f'Métricas — {MODELO} ({MODALIDAD})')
axes[1].tick_params(axis='x', rotation=30)
for i, (k, v) in enumerate(metricas.items()):
    axes[1].text(i, v + 0.01, f'{v:.3f}', ha='center', fontsize=9)

plt.tight_layout()
fig_path = f"{OUTPUT_DIR}/{EXP_ID}/visualizacion_{MODELO}_{MODALIDAD}.png"
os.makedirs(os.path.dirname(fig_path), exist_ok=True)
plt.savefig(fig_path, dpi=300, bbox_inches='tight')
plt.show()
print(f"✅ Figura guardada: {fig_path}")