# -*- coding: utf-8 -*-
"""mejor_exp_clasico_split_estratificado_(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GzvagTbc0lShOGJBQJn3TzlFEzl1JGvo
"""

# ══════════════════════════════════════════════════════════
# REPRODUCCIÓN DEL MEJOR RESULTADO — ALGORITMOS CLÁSICOS
# Regresión Logística: trigramas, sin stop words, con stemming,
# min_df=3, vectorización TF
#
# CAMBIOS respecto a versión anterior:
#   - Split 85/15 estratificado (antes: 75/25 sin estratificar)
#   - random_state=42 (antes: 0) — alineado con experimentos Transformer
#   Motivo: unificar el conjunto de prueba para comparación válida
#   entre algoritmos clásicos y modelos Transformer
# ══════════════════════════════════════════════════════════

import zipfile
import io
import json
import time
import os
import pandas as pd
import nltk
from datetime import datetime
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, classification_report, confusion_matrix
)

# ── 1. MONTAR DRIVE ───────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

# ── 2. CONFIGURACIÓN ──────────────────────────────────────
ZIP_PATH    = "/content/drive/MyDrive/PyCrim_dataset.zip"
ZIP_ARCHIVO = "corpusJurisprudence.txt"
OUTPUT_DIR  = "/content/drive/MyDrive/Proyecto/PyCrim_experiments/CLASICOS"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Semilla alineada con experimentos Transformer
SEMILLA = 42

inicio = time.time()

# ── 3. CARGAR DATASET ─────────────────────────────────────
with zipfile.ZipFile(ZIP_PATH, "r") as zipref:
    datos = io.BytesIO(zipref.read(ZIP_ARCHIVO))

data = pd.read_csv(datos, sep="\t")
print(f"Dataset cargado: {data.shape}")

# Verificar distribución de clases en dataset completo
print("\nDistribución de clases (dataset completo):")
print(data["Resultado binario de la acción"].value_counts())
print(data["Resultado binario de la acción"].value_counts(normalize=True).round(3))

# ── 4. SPLIT 85/15 ESTRATIFICADO ──────────────────────────
# test_size=0.15 → mismo 15% de prueba que experimentos Transformer
# stratify       → mantiene proporción de clases en ambos conjuntos
# random_state   → alineado con Transformer (SEMILLA=42)
X_train, X_test, y_train, y_test = train_test_split(
    data["Contenido Txt"],
    data["Resultado binario de la acción"],
    test_size=0.15,
    random_state=SEMILLA,
    stratify=data["Resultado binario de la acción"]
)
print(f"\nTrain: {len(X_train)} ({len(X_train)/len(data)*100:.1f}%) | Test: {len(X_test)} ({len(X_test)/len(data)*100:.1f}%)")

# Verificar estratificación
print("\nDistribución clases en entrenamiento:")
print(y_train.value_counts(normalize=True).round(3))
print("Distribución clases en prueba:")
print(y_test.value_counts(normalize=True).round(3))

# ── 5. STEMMING ───────────────────────────────────────────
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

stemmer = SnowballStemmer("spanish")

def stem_tokens(tokens):
    return [stemmer.stem(token) for token in tokens]

def tokenize_and_stem(text):
    tokens = nltk.word_tokenize(text.lower())
    return stem_tokens(tokens)

# ── 6. VECTORIZACIÓN ──────────────────────────────────────
print("\nVectorizando (puede tardar varios minutos)...")
vect = CountVectorizer(
    ngram_range=(3, 3),
    stop_words=None,
    tokenizer=tokenize_and_stem,
    token_pattern=None,
    min_df=3
)

X_train_vec = vect.fit_transform(X_train)
X_test_vec  = vect.transform(X_test)
print(f"Vocabulario: {len(vect.vocabulary_)} trigramas")

# ── 7. REGRESIÓN LOGÍSTICA ────────────────────────────────
clf = LogisticRegression(max_iter=2000, random_state=SEMILLA)
clf.fit(X_train_vec, y_train)
predictions = clf.predict(X_test_vec)

# ── 8. MÉTRICAS ───────────────────────────────────────────
cm       = confusion_matrix(y_test, predictions)
acc      = accuracy_score(y_test, predictions)
prec     = precision_score(y_test, predictions, average="macro", zero_division=1)
rec      = recall_score(y_test, predictions, average="macro")
f1       = f1_score(y_test, predictions, average="macro")
prec_pos = precision_score(y_test, predictions, pos_label=1, average="binary")
rec_pos  = recall_score(y_test, predictions, pos_label=1, average="binary")
f1_pos   = f1_score(y_test, predictions, pos_label=1, average="binary")
f1_neg   = f1_score(y_test, predictions, pos_label=0, average="binary")

tiempo = round((time.time() - inicio) / 60, 2)

print("\n" + "="*60)
print("RESULTADOS — REGRESIÓN LOGÍSTICA (SPLIT 85/15 ESTRATIFICADO)")
print("="*60)
print(classification_report(
    y_test, predictions,
    target_names=["No hace lugar (0)", "Hace lugar (1)"],
    digits=4
))
print(f"Exactitud:               {acc:.4f}")
print(f"Precisión Macro:         {prec:.4f}")
print(f"Exhaustividad Macro:     {rec:.4f}")
print(f"F1 Macro:                {f1:.4f}")
print(f"F1 Clase Positiva:       {f1_pos:.4f}")
print(f"F1 Clase Negativa:       {f1_neg:.4f}")
print(f"Precisión Clase Positiva:{prec_pos:.4f}")
print(f"Exhaust. Clase Positiva: {rec_pos:.4f}")
print(f"Tiempo:                  {tiempo} min")
print("="*60)

# ── 9. GUARDAR JSON ───────────────────────────────────────
config = {
    "experimento": {
        "id": "CLASICO-MEJOR-SPLIT-ESTRATIFICADO",
        "fecha": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "responsable": "Fatima Ferreira - Blanca Franco",
        "descripcion": (
            "Reproducción del mejor resultado de algoritmos clásicos — "
            "Regresión Logística configuración óptima. "
            "Split 85/15 estratificado con random_state=42 para comparación "
            "directa con experimentos Transformer (mismo conjunto de prueba)."
        )
    },
    "modelo": {
        "nombre": "Regresión Logística",
        "libreria": "scikit-learn",
        "parametros": {
            "max_iter": 2000,
            "solver": "lbfgs",
            "random_state": SEMILLA
        }
    },
    "preprocesamiento": {
        "vectorizador": "CountVectorizer (TF)",
        "ngram_range": "(3, 3)",
        "stop_words": "No",
        "stemming": "Sí — SnowballStemmer español",
        "min_df": 3
    },
    "datos": {
        "dataset": "PyCrim",
        "archivo": "corpusJurisprudence.txt",
        "zenodo": "https://zenodo.org/records/14373749",
        "split_train": 0.85,
        "split_test": 0.15,
        "split_estrategia": "estratificado",
        "random_state": SEMILLA,
        "nota_comparabilidad": (
            "test_size=0.15 y random_state=42 alineados con experimentos Transformer "
            "para garantizar que ambas familias de modelos sean evaluadas sobre "
            "exactamente el mismo conjunto de prueba."
        ),
        "total_muestras": len(data),
        "train_muestras": len(X_train),
        "test_muestras": len(X_test),
        "balance_clases": {
            "clase_0_pct": round(
                (data["Resultado binario de la acción"] == 0).sum() / len(data) * 100, 2
            ),
            "clase_1_pct": round(
                (data["Resultado binario de la acción"] == 1).sum() / len(data) * 100, 2
            )
        },
        "balance_clases_test": {
            "clase_0_n": int((y_test == 0).sum()),
            "clase_1_n": int((y_test == 1).sum()),
            "clase_0_pct": round((y_test == 0).sum() / len(y_test) * 100, 2),
            "clase_1_pct": round((y_test == 1).sum() / len(y_test) * 100, 2)
        }
    },
    "resultados": {
        "tiempo_minutos": tiempo,
        "test": {
            "exactitud":                    round(acc,      4),
            "f1_macro":                     round(f1,       4),
            "f1_clase_positiva":            round(f1_pos,   4),
            "f1_clase_negativa":            round(f1_neg,   4),
            "precision_macro":              round(prec,     4),
            "exhaustividad_macro":          round(rec,      4),
            "precision_clase_positiva":     round(prec_pos, 4),
            "exhaustividad_clase_positiva": round(rec_pos,  4)
        },
        "matriz_confusion": {
            "TP": int(cm[1, 1]),
            "TN": int(cm[0, 0]),
            "FP": int(cm[0, 1]),
            "FN": int(cm[1, 0])
        }
    }
}

path = os.path.join(OUTPUT_DIR, "config_RegresionLogistica_mejor_estratificado.json")
with open(path, "w", encoding="utf-8") as f:
    json.dump(config, f, ensure_ascii=False, indent=2)

print(f"\n✅ JSON guardado en: {path}")

# ── 10. MATRIZ DE CONFUSIÓN — GUARDAR PNG ─────────────────
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')

etiquetas = ["No hace lugar (0)", "Hace lugar (1)"]

fig, ax = plt.subplots(figsize=(6, 5))

im = ax.imshow(cm, interpolation="nearest", cmap="Blues")
plt.colorbar(im, ax=ax)

ax.set(xticks=[0, 1],
       yticks=[0, 1],
       xticklabels=etiquetas,
       yticklabels=etiquetas,
       ylabel="Etiqueta real",
       xlabel="Etiqueta predicha",
       title="Matriz de Confusión\nRegresión Logística — Split 85/15 estratificado")

# Valores dentro de cada celda
total = cm.sum()
for i in range(2):
    for j in range(2):
        valor = cm[i, j]
        pct   = valor / total * 100
        color = "white" if cm[i, j] > cm.max() / 2 else "black"
        ax.text(j, i, f"{valor}\n({pct:.1f}%)",
                ha="center", va="center",
                fontsize=12, color=color, fontweight="bold")

plt.xticks(rotation=15, ha="right")
plt.tight_layout()

# Guardar en Drive
PNG_PATH = os.path.join(OUTPUT_DIR, "confusion_matrix_LR_estratificado.png")
plt.savefig(PNG_PATH, dpi=150, bbox_inches="tight")
plt.show()
print(f"✅ PNG guardado en: {PNG_PATH}")



if result_commit.returncode == 0:
    subprocess.run(["git", "-C", REPO_PATH, "push", REPO_URL, "main"], check=True)
    print(f"✅ Resultados subidos a GitHub — {commit_msg}")
else:
    print("⚠️ Nada nuevo para commitear")
