# -*- coding: utf-8 -*-
"""template_utimo_transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10gyiyVUlVghX8w3zyD0lDCo6rxU0VmuM

# Experimento: [MODELO] — [MODALIDAD]

**Proyecto:** Aplicación de modelos Transformers para la clasificación de casos judiciales — PyCrim  
**Dataset:** PyCrim — Sala Penal, Corte Suprema de Justicia del Paraguay  
**Responsable:** Fatima Ferreira - Blanca Franco  
**Fecha:** 23/03/2026

---
### Antes de correr este notebook:
1. Cambiar `EXP_ID`, `MODELO` y `MODALIDAD` en la celda de configuración
2. Verificar que el runtime tiene GPU activada (Entorno de ejecución → T4 GPU)
3. Montar Google Drive (se hace automáticamente en la celda 5)

## 0. Instalación de dependencias
"""

!pip install transformers datasets scikit-learn torch --quiet

"""## 1. Configuración
⚠️ **SOLO TOCAR ESTA CELDA — cambiar los 4 primeros valores**
"""

# ══════════════════════════════════════════════════════════
# COMPLETAR ANTES DE CORRER
# ══════════════════════════════════════════════════════════
EXP_ID      = "EXP-018"          # EXP-001 a EXP-006
MODELO      = "BETO"            # "BETO" | "mBERT" | "XLM-RoBERTa"
MODALIDAD   = "con_fine_tuning"  # "sin_fine_tuning" | "con_fine_tuning"
RESPONSABLE = "Fatima Ferreira - Blanca Franco"

# ══════════════════════════════════════════════════════════
# NO MODIFICAR — hiperparámetros fijos para reproducibilidad
# ══════════════════════════════════════════════════════════
SEMILLA       = 42
MAX_LENGTH    = 512
STRIDE        = 384
LEARNING_RATE = 5e-6 #1e-5 #3e-5 se ajusta para xml-roberta
EPOCHS        = 7
BATCH_SIZE    = 16

# Rutas
ZIP_PATH    = "/content/drive/MyDrive/PyCrim_dataset.zip"
ZIP_ARCHIVO = "corpusJurisprudence.txt"
OUTPUT_DIR  = "/content/drive/MyDrive/Proyecto/PyCrim_experiments"

# Columnas del dataset
COLUMNA_TEXTO = "Contenido Txt"
COLUMNA_LABEL = "Resultado binario de la acción"

# Mapa de modelos HuggingFace — NO modificar
MODELOS_HF = {
    "BETO":        "dccuchile/bert-base-spanish-wwm-cased",
    "mBERT":       "google-bert/bert-base-multilingual-cased",
    "XLM-RoBERTa": "FacebookAI/xlm-roberta-base",
}
MODEL_NAME = MODELOS_HF[MODELO]

print(f"Experimento: {EXP_ID}")
print(f"Modelo:      {MODELO} → {MODEL_NAME}")
print(f"Modalidad:   {MODALIDAD}")
print(f"Semilla:     {SEMILLA}")

"""## 2. Semilla fija — SIEMPRE antes de cualquier otra cosa"""

import random, os
import numpy as np
import torch

def set_seed(seed=42):
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    print(f"✓ Semilla fijada: {seed}")
    print(f"✓ GPU disponible: {torch.cuda.is_available()}")
    if torch.cuda.is_available():
        print(f"✓ GPU: {torch.cuda.get_device_name(0)}")

set_seed(SEMILLA)

"""## 3. Imports"""

import zipfile, io, json, time, platform
from datetime import datetime
from collections import defaultdict

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, precision_recall_fscore_support,
    f1_score, precision_score, recall_score,
    classification_report, confusion_matrix
)

from transformers import (
    AutoTokenizer, AutoModel,
    AutoModelForSequenceClassification,
    TrainingArguments, Trainer, EarlyStoppingCallback
)
from datasets import Dataset
from google.colab import drive

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"✓ Imports OK | Device: {device}")

"""## 4. Logger automático de experimentos"""

class ExperimentLogger:
    """Guarda automáticamente config + resultados en JSON al terminar."""

    def __init__(self, exp_id, modelo, modalidad, responsable,
                 semilla, epochs, batch_size, learning_rate,
                 max_length, stride, output_dir):
        self.exp_id     = exp_id
        self.modelo     = modelo
        self.modalidad  = modalidad
        self.output_dir = output_dir
        self.inicio     = time.time()

        import sys, transformers as tr
        gpu = torch.cuda.get_device_name(0) if torch.cuda.is_available() else "no disponible"
        try:
            import google.colab
            plataforma = "Google Colab"
        except ImportError:
            plataforma = f"local ({platform.system()})"

        self.config = {
            "experimento": {
                "id": exp_id,
                "fecha": datetime.now().strftime("%Y-%m-%d %H:%M"),
                "responsable": responsable,
                "descripcion": f"{modelo} {modalidad.replace('_',' ')} — semilla {semilla}",
                "semilla": semilla,
            },
            "modelo": {
                "nombre": modelo,
                "nombre_huggingface": MODELOS_HF.get(modelo, "COMPLETAR"),
                "modalidad": modalidad,
                "num_labels": 2,
            },
            "tokenizacion": {
                "max_length": max_length,
                "stride": stride,
                "estrategia": "sliding_window_manual",
                "padding": "manual_con_pad_token_id",
            },
            "entrenamiento": {
                "epochs": epochs,
                "batch_size": batch_size,
                "learning_rate": learning_rate,
                "weight_decay": 0.01,
                "optimizer": "AdamW",
                "warmup_steps": 500, #300,
                "fp16": True,
                "early_stopping_patience": 3,#2,
                "class_weights": True,
                "aggregacion_predicciones": "promedio_probabilidades_por_documento",
            },
            "datos": {
                "dataset": "PyCrim",
                "archivo": "corpusJurisprudence.txt",
                "zenodo": "https://zenodo.org/records/14373749",
                "split_train": 0.70, "split_val": 0.15, "split_test": 0.15,
                "split_estrategia": "aleatorio_estratificado",
                "random_state": semilla,
                "total_muestras": 5000,
                "balance_clases": {"clase_0_pct": 80.94, "clase_1_pct": 19.06},

            },
            "entorno": {
                "python_version": sys.version.split()[0],
                "torch_version": torch.__version__,
                "transformers_version": tr.__version__,
                "plataforma": plataforma,
                "gpu": gpu,
            },
            "resultados": None,
        }
        print(f"\n[Logger] {exp_id} iniciado — {modelo} {modalidad}")

    def guardar_resultados(self, accuracy, f1_macro, f1_positiva, f1_negativa,
                           precision_macro, recall_macro,
                           precision_positiva=None, recall_positiva=None,
                           tp=None, tn=None, fp=None, fn=None,
                           mejor_epoch=None, tiempo_minutos=None):

        if tiempo_minutos is None:
            tiempo_minutos = round((time.time() - self.inicio) / 60, 2)

        self.config["resultados"] = {
            "tiempo_minutos": tiempo_minutos,
            "mejor_epoch": mejor_epoch,
            "test": {
                "accuracy":                 round(accuracy, 4),
                "f1_macro":                 round(f1_macro, 4),
                "f1_clase_positiva":        round(f1_positiva, 4),
                "f1_clase_negativa":        round(f1_negativa, 4),
                "precision_macro":          round(precision_macro, 4),
                "recall_macro":             round(recall_macro, 4),
                "precision_clase_positiva": round(precision_positiva, 4) if precision_positiva else None,
                "recall_clase_positiva":    round(recall_positiva, 4) if recall_positiva else None,
            },
            "matriz_confusion": {"TP": tp, "TN": tn, "FP": fp, "FN": fn},
        }

        carpeta = os.path.join(self.output_dir, self.exp_id)
        os.makedirs(carpeta, exist_ok=True)
        path = os.path.join(carpeta, f"config_{self.modelo}_{self.modalidad}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(self.config, f, ensure_ascii=False, indent=2)

        t = self.config["resultados"]["test"]
        print("\n" + "="*50)
        print(f"  {self.exp_id}: {self.modelo} ({self.modalidad})")
        print("="*50)
        print(f"  Accuracy:    {t['accuracy']:.4f}")
        print(f"  F1 Macro:    {t['f1_macro']:.4f}")
        print(f"  F1 Positiva: {t['f1_clase_positiva']:.4f}")
        print(f"  F1 Negativa: {t['f1_clase_negativa']:.4f}")
        print(f"  Tiempo:      {tiempo_minutos} min")
        print(f"  Guardado en: {path}")
        print("="*50)
        return path


# Inicializar con los valores de la celda 1
logger = ExperimentLogger(
    exp_id=EXP_ID, modelo=MODELO, modalidad=MODALIDAD,
    responsable=RESPONSABLE, semilla=SEMILLA,
    epochs=EPOCHS, batch_size=BATCH_SIZE,
    learning_rate=LEARNING_RATE,
    max_length=MAX_LENGTH, stride=STRIDE,
    output_dir=OUTPUT_DIR,
)

"""## 5. Carga de datos"""

drive.mount('/content/drive')

with zipfile.ZipFile(ZIP_PATH, 'r') as zipref:
    datos = io.BytesIO(zipref.read(ZIP_ARCHIVO))

data = pd.read_csv(datos, sep="\t")
data['doc_id'] = range(len(data))

print("=" * 60)
print("DATASET CARGADO")
print("=" * 60)
print(f"Total documentos: {len(data)}")
print("\nDistribución de clases:")
print(data[COLUMNA_LABEL].value_counts())
print(f"\nDesbalanceo: {data[COLUMNA_LABEL].value_counts(normalize=True)[0]:.2%} clase 0")

# División 70/15/15 estratificada
train_df, temp_df = train_test_split(
    data, test_size=0.30,
    stratify=data[COLUMNA_LABEL],
    random_state=SEMILLA
)
val_df, test_df = train_test_split(
    temp_df, test_size=0.50,
    stratify=temp_df[COLUMNA_LABEL],
    random_state=SEMILLA
)

print(f"\nDivisión:")
print(f"  Train: {len(train_df)} documentos")
print(f"  Val:   {len(val_df)} documentos")
print(f"  Test:  {len(test_df)} documentos")

X_train, y_train = train_df[COLUMNA_TEXTO].values, train_df[COLUMNA_LABEL].values
X_val,   y_val   = val_df[COLUMNA_TEXTO].values,   val_df[COLUMNA_LABEL].values
X_test,  y_test  = test_df[COLUMNA_TEXTO].values,  test_df[COLUMNA_LABEL].values
doc_ids_train    = train_df["doc_id"].values
doc_ids_val      = val_df["doc_id"].values
doc_ids_test     = test_df["doc_id"].values

print("\n✅ Datos preprocesados y divididos")

"""## 6. Tokenización con sliding window"""

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize_sliding_window(texts, labels, doc_ids):
    """Fragmenta documentos largos con solapamiento."""
    all_data = {"input_ids": [], "attention_mask": [], "labels": [], "doc_id": []}

    for text, label, doc_id in zip(texts, labels, doc_ids):
        tokens = tokenizer(str(text), truncation=False)["input_ids"]

        if len(tokens) <= MAX_LENGTH:
            enc = tokenizer(str(text), padding="max_length", truncation=True, max_length=MAX_LENGTH)
            all_data["input_ids"].append(enc["input_ids"])
            all_data["attention_mask"].append(enc["attention_mask"])
            all_data["labels"].append(label)
            all_data["doc_id"].append(doc_id)
        else:
            for i in range(0, len(tokens), STRIDE):
                chunk = tokens[i:i + MAX_LENGTH]
                mask  = [1] * len(chunk)

                if len(chunk) < MAX_LENGTH:
                    chunk += [tokenizer.pad_token_id] * (MAX_LENGTH - len(chunk))
                    mask  += [0] * (MAX_LENGTH - len(mask))

                all_data["input_ids"].append(chunk)
                all_data["attention_mask"].append(mask)
                all_data["labels"].append(label)
                all_data["doc_id"].append(doc_id)

                if i + MAX_LENGTH >= len(tokens):
                    break

    print(f"  {len(texts)} docs → {len(all_data['labels'])} fragmentos ({len(all_data['labels'])/len(texts):.1f} promedio)")
    return Dataset.from_dict(all_data)

print("=" * 60)
print("TOKENIZACIÓN CON SLIDING WINDOW")
print("=" * 60)
print(f"MAX_LENGTH={MAX_LENGTH} | STRIDE={STRIDE}")
print("\nTrain:")
train_dataset = tokenize_sliding_window(X_train, y_train, doc_ids_train)
print("Val:")
val_dataset   = tokenize_sliding_window(X_val,   y_val,   doc_ids_val)
print("Test:")
test_dataset  = tokenize_sliding_window(X_test,  y_test,  doc_ids_test)
print("\n✅ Tokenización completada")

"""## 7. Experimento
> Si `MODALIDAD == 'sin_fine_tuning'` → extrae embeddings (CLS token) + Regresión Logística  
> Si `MODALIDAD == 'con_fine_tuning'` → fine-tuning completo con WeightedTrainer + agregación por documento
"""

# Pesos de clase para el desbalance 80/20 — se usa en ambas modalidades//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////,p 6666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666'00000)
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float).to(device)
print(f"Pesos de clase: {class_weights.round(3)}")


if MODALIDAD == "sin_fine_tuning":
    # ── SIN FINE-TUNING ───────────────────────────────────────
    print("\n" + "=" * 60)
    print("EXPERIMENTO: SIN FINE-TUNING")
    print("=" * 60)

    # Cargar modelo base (sin cabeza de clasificación)
    model_base = AutoModel.from_pretrained(MODEL_NAME).to(device)
    model_base.eval()

    def extract_embeddings_doc(texts, doc_ids):
        """Extrae embeddings con sliding window y promedia por documento."""
        embeddings = []
        for text, doc_id in zip(texts, doc_ids):
            tokens   = tokenizer(str(text), truncation=False)["input_ids"]
            doc_embs = []

            if len(tokens) <= MAX_LENGTH:
                inputs = tokenizer(str(text), return_tensors="pt",
                                   max_length=MAX_LENGTH, truncation=True, padding=True).to(device)
                with torch.no_grad():
                    outputs = model_base(**inputs)
                doc_embs.append(outputs.last_hidden_state[:, 0, :].cpu().numpy()[0])
            else:
                for i in range(0, len(tokens), STRIDE):
                    chunk = tokens[i:i + MAX_LENGTH]
                    if len(chunk) < MAX_LENGTH:
                        chunk += [tokenizer.pad_token_id] * (MAX_LENGTH - len(chunk))
                    chunk_text = tokenizer.decode(chunk, skip_special_tokens=False)
                    inputs = tokenizer(chunk_text, return_tensors="pt",
                                       max_length=MAX_LENGTH, truncation=True, padding=True).to(device)
                    with torch.no_grad():
                        outputs = model_base(**inputs)
                    doc_embs.append(outputs.last_hidden_state[:, 0, :].cpu().numpy()[0])
                    if i + MAX_LENGTH >= len(tokens):
                        break

            embeddings.append(np.mean(doc_embs, axis=0))
        return np.array(embeddings)

    print("Extrayendo embeddings (puede tardar ~20-30 min)...")
    print("Train...")
    X_train_emb = extract_embeddings_doc(X_train, doc_ids_train)
    print("Test...")
    X_test_emb  = extract_embeddings_doc(X_test,  doc_ids_test)

    print("\nEntrenando Regresión Logística...")
    clf = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=SEMILLA)
    clf.fit(X_train_emb, y_train)

    y_pred      = clf.predict(X_test_emb)
    y_true      = y_test
    mejor_epoch = None


else:
    # ── CON FINE-TUNING ───────────────────────────────────────
    print("\n" + "=" * 60)
    print("EXPERIMENTO: CON FINE-TUNING")
    print("=" * 60)

    model_ft = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)

    class WeightedTrainer(Trainer):
        def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
            labels  = inputs.pop("labels")
            outputs = model(**inputs)
            loss_fct= torch.nn.CrossEntropyLoss(weight=class_weights_tensor)
            loss    = loss_fct(outputs.logits, labels)
            return (loss, outputs) if return_outputs else loss

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=-1)
        acc   = accuracy_score(labels, preds)
        #_, _, f1, _ = precision_recall_fscore_support(labels, preds, average="weighted", zero_division=0)
        f1 = f1_score(labels, preds, average='macro')  # era 'weighted'
        return {"accuracy": acc, "f1": f1}



    training_args = TrainingArguments(
        output_dir                  = f"{OUTPUT_DIR}/{EXP_ID}/checkpoints",
        save_steps                  = 100,
        eval_strategy               = "epoch",
        save_strategy               = "epoch",
        learning_rate               = LEARNING_RATE,
        per_device_train_batch_size = BATCH_SIZE,
        per_device_eval_batch_size  = 32,
        num_train_epochs            = EPOCHS,
        weight_decay                = 0.01,
        warmup_steps                = 500,#300,
        load_best_model_at_end      = True,
        metric_for_best_model       = "f1", #f1 se comenta para otra prueba
        logging_steps               = 150,
        fp16                        = True,
        save_total_limit            = 2,
        seed                        = SEMILLA,
        report_to                   = "none",
    )

    trainer = WeightedTrainer(
        model           = model_ft,
        args            = training_args,
        train_dataset   = train_dataset,
        eval_dataset    = val_dataset,
        compute_metrics = compute_metrics,
        callbacks       = [EarlyStoppingCallback(early_stopping_patience=3)]
    )

    print("\n⚡ Iniciando entrenamiento...")
    #el trainer.train() se comenta cuando se habia cortado y se vuelve a ejecutar pero desde el ultimo checkpoint
    #hay que volver a dejar sin descomentar cuando se entrene un nuevo modelo
    trainer.train()
    # Si se cortó, retomar desde el último checkpoint
    #CHECKPOINT = f"{OUTPUT_DIR}/{EXP_ID}/checkpoints/checkpoint-10145"  # ← el número más alto
    #trainer.train(resume_from_checkpoint=CHECKPOINT)

    print("\n✅ Entrenamiento completado")


print("\n✅ Experimento completado")

# Agregación por documento: promedia probabilidades de todos sus fragmentos
    def aggregate_predictions(logits, doc_ids, labels, threshold=0.5):
        probs    = torch.softmax(torch.tensor(logits), dim=-1).numpy()
        doc_data = defaultdict(lambda: {"probs": [], "label": None})
        for prob, doc_id, label in zip(probs, doc_ids, labels):
            doc_data[doc_id]["probs"].append(prob)
            doc_data[doc_id]["label"] = label
        preds, true_labels = [], []
        for doc_id in sorted(doc_data.keys()):
            avg_prob = np.mean(doc_data[doc_id]["probs"], axis=0)
            #threshold = 0.38
            #probs = np.array(doc_data[doc_id]["probs"])
            #avg_prob = 0.5*np.mean(probs, axis=0) + 0.5*np.max(probs, axis=0)
            preds.append(1 if avg_prob[1] >= threshold else 0)
            #preds.append(np.argmax(avg_prob))
            true_labels.append(doc_data[doc_id]["label"])
        return np.array(preds), np.array(true_labels)


     # Predicciones sobre val set para buscar umbral
    val_predictions = trainer.predict(val_dataset)

    # Probar umbrales entre 0.20 y 0.60
    thresholds = np.arange(0.50, 0.601, 0.005)
    resultados_umbral = []
    for t in thresholds:
        preds_val, true_val = aggregate_predictions(
            val_predictions.predictions,
            val_dataset["doc_id"],
            val_dataset["labels"],
            threshold=t
        )
        f1_val = f1_score(true_val, preds_val, average='macro')
        resultados_umbral.append((round(t, 3), round(f1_val, 4)))

    mejor_umbral, mejor_f1_val = max(resultados_umbral, key=lambda x: x[1])
    print(f"\nTop 5 umbrales por F1 macro en validación:")
    for t, f in sorted(resultados_umbral, key=lambda x: x[1], reverse=True)[:5]:
        print(f"  umbral={t:.2f} → F1 macro val={f:.4f}")
    print(f"\n✅ Umbral óptimo seleccionado: {mejor_umbral} (F1 val={mejor_f1_val:.4f})")

    # ── EVALUACIÓN FINAL EN TEST SET CON UMBRAL ÓPTIMO ────────
    predictions = trainer.predict(test_dataset)
    y_pred, y_true = aggregate_predictions(
        predictions.predictions,
        test_dataset["doc_id"],
        test_dataset["labels"],
        threshold=mejor_umbral
    )
    mejor_epoch = trainer.state.best_model_checkpoint

"""## 8. Evaluación y guardado automático de resultados"""

print("\n" + "=" * 60)
print("EVALUACIÓN")
print("=" * 60)

print(classification_report(y_true, y_pred, target_names=['No hace lugar', 'Hace lugar'], digits=4))

cm       = confusion_matrix(y_true, y_pred)
acc      = accuracy_score(y_true, y_pred)
f1_mac   = f1_score(y_true, y_pred, average='macro')
f1_pos   = f1_score(y_true, y_pred, pos_label=1, average='binary')
f1_neg   = f1_score(y_true, y_pred, pos_label=0, average='binary')
prec_mac = precision_score(y_true, y_pred, average='macro')
rec_mac  = recall_score(y_true, y_pred, average='macro')
prec_pos = precision_score(y_true, y_pred, pos_label=1, average='binary')
rec_pos  = recall_score(y_true, y_pred, pos_label=1, average='binary')

# Guardar JSON automáticamente
logger.guardar_resultados(
    accuracy           = acc,
    f1_macro           = f1_mac,
    f1_positiva        = f1_pos,
    f1_negativa        = f1_neg,
    precision_macro    = prec_mac,
    recall_macro       = rec_mac,
    precision_positiva = prec_pos,
    recall_positiva    = rec_pos,
    tp  = int(cm[1,1]), tn = int(cm[0,0]),
    fp  = int(cm[0,1]), fn = int(cm[1,0]),
    mejor_epoch = mejor_epoch,
)

# Guardar predicciones para Bootstrap/McNemar
np.save(f"{OUTPUT_DIR}/{EXP_ID}/y_true_{MODELO}_{MODALIDAD}.npy", y_true)
np.save(f"{OUTPUT_DIR}/{EXP_ID}/y_pred_{MODELO}_{MODALIDAD}.npy", y_pred)
print("✅ Predicciones guardadas")

"""## 9. Visualizaciones"""

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[0],
            xticklabels=['No', 'Sí'], yticklabels=['No', 'Sí'])
axes[0].set_title(f'Matriz de Confusión\n{MODELO} — {MODALIDAD}')
axes[0].set_ylabel('Verdadero')
axes[0].set_xlabel('Predicho')

metricas = {'Accuracy': acc, 'F1 Macro': f1_mac,
            'F1 Positiva': f1_pos, 'F1 Negativa': f1_neg,
            'Precision': prec_mac, 'Recall': rec_mac}
axes[1].bar(metricas.keys(), metricas.values(), color='steelblue')
axes[1].set_ylim(0, 1)
axes[1].set_title(f'Métricas — {MODELO} ({MODALIDAD})')
axes[1].tick_params(axis='x', rotation=30)
for i, (k, v) in enumerate(metricas.items()):
    axes[1].text(i, v + 0.01, f'{v:.3f}', ha='center', fontsize=9)

plt.tight_layout()
fig_path = f"{OUTPUT_DIR}/{EXP_ID}/visualizacion_{MODELO}_{MODALIDAD}.png"
os.makedirs(os.path.dirname(fig_path), exist_ok=True)
plt.savefig(fig_path, dpi=300, bbox_inches='tight')
plt.show()
print(f"✅ Figura guardada: {fig_path}")

"""## 10. Subir resultados a GitHub"""

commit_msg = f"{EXP_ID}: {MODELO} {MODALIDAD} — con ajuste en parametro  F1 macro: {f1_mac:.4f}"
print(f"Mensaje de commit sugerido:")
print(f'  git commit -m "{commit_msg}"')

import os, shutil, subprocess

# Leer token
with open("/content/drive/MyDrive/Proyecto/github_token.txt") as f:
    token = f.read().strip()

GITHUB_USER = "blanqui-franco"
GITHUB_REPO = "pycrim-transformers"   # ← solo el nombre, sin URL
REPO_PATH   = f"/content/{GITHUB_REPO}"
REPO_URL    = f"https://{token}@github.com/{GITHUB_USER}/{GITHUB_REPO}.git"

# Clonar si no existe, actualizar si ya existe
if not os.path.exists(REPO_PATH):
    subprocess.run(["git", "clone", REPO_URL, REPO_PATH], check=True)
    print("✅ Repo clonado")
else:
    subprocess.run(["git", "-C", REPO_PATH, "pull"], check=True)
    print("✅ Repo actualizado")

# Configurar identidad
subprocess.run(["git", "-C", REPO_PATH, "config", "user.email", "blanquisaldivar9@gmail.com"], check=True)
subprocess.run(["git", "-C", REPO_PATH, "config", "user.name", "blanqui-franco"], check=True)

# Copiar archivos al repo
carpeta_destino = os.path.join(REPO_PATH, "experiments", EXP_ID)
os.makedirs(carpeta_destino, exist_ok=True)

shutil.copy(f"{OUTPUT_DIR}/{EXP_ID}/config_{MODELO}_{MODALIDAD}.json", carpeta_destino)
shutil.copy(f"{OUTPUT_DIR}/{EXP_ID}/visualizacion_{MODELO}_{MODALIDAD}.png", carpeta_destino)

# Commit y push
subprocess.run(["git", "-C", REPO_PATH, "add", f"experiments/{EXP_ID}/"], check=True)
subprocess.run(["git", "-C", REPO_PATH, "commit", "-m", commit_msg], check=True)
subprocess.run(["git", "-C", REPO_PATH, "push", REPO_URL, "main"], check=True)

print(f"✅ Resultados subidos a GitHub — {commit_msg}")